packages:
  - 'api'

injectWorkspacePackages: true

allowBuilds:
  esbuild: true
  fsevents: true
  lefthook: true
  msgpackr-extract: false
  msw: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@evespace/esi-client@2.0.0'
