import { describe, expect, it } from 'vitest';

import {
  createOperationAccountingReport,
  createJsonProvenanceHeader,
  createProvenanceHeader,
  renderGeneratedBarrel,
  renderGeneratedJson,
} from '../scripts/generate/artifacts.mjs';
import type { NormalizedOpenApiModel } from '../scripts/generate/normalize.mjs';
import type { ResolvedOperationMetadata } from '../scripts/generate/operation-metadata.mjs';

const provenance = {
  compatibilityDate: '2026-08-18',
  sha256: 'a'.repeat(64),
};

describe('generated artifact helpers', () => {
  it('renders deterministic provenance headers for TypeScript, Markdown, and JSON-compatible text', () => {
    expect(createProvenanceHeader(provenance, 'typescript')).toBe(
      `// @generated by @evespace/esi-client.\n// Compatibility date: 2026-08-18.\n// Specification SHA-256: ${'a'.repeat(64)}.\n// DO NOT EDIT.\n`,
    );
    expect(createProvenanceHeader(provenance, 'json-compatible')).toBe(
      createProvenanceHeader(provenance, 'typescript'),
    );
    expect(createProvenanceHeader(provenance, 'markdown')).toBe(
      `<!--\n@generated by @evespace/esi-client.\nCompatibility date: 2026-08-18.\nSpecification SHA-256: ${'a'.repeat(64)}.\nDO NOT EDIT.\n-->\n`,
    );
  });

  it('sorts generated barrel exports and rejects duplicates or unsafe specifiers', () => {
    const barrel = renderGeneratedBarrel(['./zeta.js', './alpha.js'], provenance);
    expect(barrel.indexOf("export * from './alpha.js';")).toBeLessThan(
      barrel.indexOf("export * from './zeta.js';"),
    );
    expect(() => renderGeneratedBarrel(['./alpha.js', './alpha.js'], provenance)).toThrow(
      'Duplicate generated barrel module specifier',
    );
    expect(() => renderGeneratedBarrel(['../maintained.js'], provenance)).toThrow(
      'Invalid generated barrel module specifier',
    );
  });

  it('creates explicit sorted generated/excluded operation accounting', () => {
    const model = accountingModel();
    const report = createOperationAccountingReport(model, [metadata('get_item')]);

    expect(report).toEqual({
      schemaVersion: 1,
      summary: { source: 2, generated: 1, excluded: 1 },
      operations: [
        {
          operationId: 'delete_item',
          reason: { code: 'unsupported-test', detail: 'Excluded by fixture.' },
          status: 'excluded',
        },
        {
          classification: 'read',
          facade: { domain: 'items', method: 'getItem' },
          operationId: 'get_item',
          status: 'generated',
        },
      ],
    });
    expect(Object.isFrozen(report.operations)).toBe(true);
  });

  it('renders valid deterministic JSON with first-class provenance metadata', () => {
    const first = renderGeneratedJson({ zeta: true, alpha: 'value' }, provenance);
    const second = renderGeneratedJson({ alpha: 'value', zeta: true }, provenance);

    expect(second).toBe(first);
    expect(JSON.parse(first)).toEqual({
      _generated: {
        compatibilityDate: '2026-08-18',
        notice: 'Generated by @evespace/esi-client. DO NOT EDIT.',
        specificationSha256: 'a'.repeat(64),
      },
      alpha: 'value',
      zeta: true,
    });
    expect(Object.isFrozen(Object.values(createJsonProvenanceHeader(provenance))[0])).toBe(true);
  });

  it('rejects incomplete operation metadata accounting', () => {
    expect(() => createOperationAccountingReport(accountingModel(), [])).toThrow(
      'Operation metadata does not cover every generated operation',
    );
  });
});

function metadata(operationId: string): ResolvedOperationMetadata {
  return {
    operationId,
    domain: 'items',
    method: 'getItem',
    classification: 'read',
    safetyOverrideReason: null,
  };
}

function accountingModel(): NormalizedOpenApiModel {
  return {
    operations: [
      {
        operationId: 'get_item',
        method: 'GET',
        path: '/items',
        domainSource: 'Items',
        tags: ['Items'],
        summary: null,
        description: null,
        parameters: [],
        requestBody: null,
        successResponses: [],
        security: [],
        pagination: { kind: 'none', requestParameters: [], responseHeaders: [] },
        cache: { responseHeaders: [], extensions: {} },
        extensions: {},
      },
    ],
    models: [],
    exclusions: [
      {
        operationId: 'delete_item',
        reason: { code: 'unsupported-test', detail: 'Excluded by fixture.' },
        reviewed: true,
      },
    ],
    inventory: { openapi: [], schemas: [] },
    accounting: {
      sourceOperationIds: ['delete_item', 'get_item'],
      normalizedOperationIds: ['get_item'],
      excludedOperationIds: ['delete_item'],
    },
  };
}
