import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, readdir, rename, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  orchestrateGeneration,
  type EmitterContext,
  type GeneratedOutputClaim,
  type GeneratedOutputEmitter,
  type OrchestrateGenerationOptions,
} from '../scripts/generate/orchestrate.ts';
import { generatedReplacementTargets } from '../scripts/generate/paths.ts';
import { makeTemporaryDirectory } from './helpers/temporary-directory.js';

const fileTargets = new Set(['llms.txt', 'docs/llms.txt']);
const openApiDocument = {
  openapi: '3.1.0',
  info: { title: 'Before correction', version: '1.0.0' },
  paths: {
    '/items': {
      get: {
        operationId: 'before_operation',
        responses: { '204': { description: 'No content' } },
      },
    },
  },
};

describe('generation orchestration', () => {
  it('replaces every declared file and directory from corrected, normalized staged output', async () => {
    const fixture = await makeFixture();
    const manifestPath = await writeCorrectionManifest(fixture.projectRoot);
    let emitterOutputDirectory = '';
    let emitterOperationMetadata: EmitterContext['operationMetadata'] = [];
    let emitterNamingReviewReport = '';

    const result = await orchestrateGeneration({
      ...baseOptions(fixture),
      corrections: { manifestPath },
      emitters: [
        outputEmitter(async (context) => {
          emitterOutputDirectory = context.outputDirectory;
          emitterOperationMetadata = context.operationMetadata;
          emitterNamingReviewReport = context.namingReviewReport;
          await writeExternalOutputs(context);
          return externalClaims();
        }),
      ],
    });

    expect(relative(fixture.temporaryRoot, emitterOutputDirectory)).not.toMatch(/^\.\./u);
    expect(relative(fixture.projectRoot, emitterOutputDirectory)).toMatch(/^\.\./u);
    expect(emitterOperationMetadata).toEqual([
      {
        classification: 'read',
        domain: 'after',
        method: 'afterOperation',
        operationId: 'after_operation',
        safetyOverrideReason: null,
      },
    ]);
    expect(result.replacedTargets).toEqual(generatedReplacementTargets);
    await expect(readFile(join(fixture.projectRoot, 'llms.txt'), 'utf8')).resolves.toBe(
      'new llms.txt\n',
    );
    await expect(
      readFile(join(fixture.projectRoot, 'src/generated/generated.txt'), 'utf8'),
    ).resolves.toBe('new src/generated\n');

    const snapshotPath = join(fixture.projectRoot, 'openapi/generated/esi-openapi.json');
    const snapshot = await readFile(snapshotPath, 'utf8');
    expect(JSON.parse(snapshot)).toMatchObject({ info: { title: 'After correction' } });
    const model = JSON.parse(
      await readFile(join(fixture.projectRoot, 'openapi/generated/normalized-model.json'), 'utf8'),
    );
    expect(model.accounting).toEqual({
      excludedOperationIds: [],
      normalizedOperationIds: ['after_operation'],
      sourceOperationIds: ['after_operation'],
    });
    const provenance = JSON.parse(
      await readFile(join(fixture.projectRoot, 'openapi/generated/provenance.json'), 'utf8'),
    );
    expect(provenance).toMatchObject({
      appliedCorrections: ['correct-title'],
      compatibilityDate: '2026-08-18',
      facadeCatalog: {
        path: '../facade-catalog.json',
        sha256: createHash('sha256')
          .update(await readFile(fixture.facadeCatalogPath, 'utf8'))
          .digest('hex'),
      },
      facadeReviewReport: {
        path: 'docs/generated/facade-naming-review.md',
        sha256: createHash('sha256').update(emitterNamingReviewReport).digest('hex'),
      },
      sha256: createHash('sha256').update(snapshot).digest('hex'),
      specificationUrl: 'https://example.test/openapi.json',
    });
    expect(emitterNamingReviewReport).not.toContain(provenance.facadeReviewReport.sha256);
    const accounting = JSON.parse(
      await readFile(
        join(fixture.projectRoot, 'openapi/generated/operation-accounting.json'),
        'utf8',
      ),
    );
    expect(accounting).toEqual({
      _generated: {
        compatibilityDate: '2026-08-18',
        notice: 'Generated by @evespace/esi-client. DO NOT EDIT.',
        specificationSha256: provenance.sha256,
      },
      operations: [
        {
          classification: 'read',
          facade: { domain: 'after', method: 'afterOperation' },
          operationId: 'after_operation',
          status: 'generated',
        },
      ],
      schemaVersion: 1,
      summary: { excluded: 0, generated: 1, source: 1 },
    });
    await expectMaintainedFiles(fixture);
    await expectNoTransactionDebris(fixture);
  });

  it('produces byte-equivalent output for unchanged inputs', async () => {
    const fixture = await makeFixture();
    const options = baseOptions(fixture);

    await orchestrateGeneration(options);
    const first = await snapshotGeneratedOutputs(fixture.projectRoot);
    await orchestrateGeneration(options);
    const second = await snapshotGeneratedOutputs(fixture.projectRoot);

    expect(second).toEqual(first);
    await expectNoTransactionDebris(fixture);
  });

  it.each([
    'retrieval',
    'correction',
    'normalization',
    'emitter',
    'materialization',
    'replacement',
  ] as const)(
    'preserves every prior output and maintained file when %s fails',
    async (failurePoint) => {
      const fixture = await makeFixture();
      const options = baseOptions(fixture);
      let failedReplacement = false;
      let materializationCount = 0;

      if (failurePoint === 'retrieval') {
        options.openapi = {
          ...options.openapi,
          fetchImplementation: async () => new Response('unavailable', { status: 503 }),
        };
      }
      if (failurePoint === 'correction') {
        options.corrections = {
          manifestPath: await writeCorrectionManifest(fixture.projectRoot, 'stale title'),
        };
      }
      if (failurePoint === 'normalization') {
        options.dependencies = {
          normalizeOpenApiDocument: async () => {
            throw new Error('normalization failed');
          },
        };
      }
      if (failurePoint === 'emitter') {
        options.emitters = [
          outputEmitter(async () => {
            throw new Error('emitter failed');
          }),
        ];
      }
      if (failurePoint === 'materialization') {
        options.dependencies = {
          materializePath: async (source, destination) => {
            materializationCount += 1;
            if (materializationCount === 3) throw new Error('materialization failed');
            await cp(source, destination, {
              errorOnExist: true,
              force: false,
              recursive: true,
            });
          },
        };
      }
      if (failurePoint === 'replacement') {
        options.dependencies = {
          replacePath: async (source, destination, phase) => {
            if (
              !failedReplacement &&
              phase === 'install' &&
              destination.endsWith(join('docs', 'generated'))
            ) {
              failedReplacement = true;
              throw new Error('replacement failed');
            }
            await rename(source, destination);
          },
        };
      }

      await expect(orchestrateGeneration(options)).rejects.toThrow(/[Ff]ailed|HTTP 503/u);
      await expectPriorOutputs(fixture);
      await expectMaintainedFiles(fixture);
      await expectNoTransactionDebris(fixture);
    },
  );

  it.each([
    {
      name: 'missing',
      claims: externalClaims().filter(({ target }) => target !== 'tests/generated'),
      message: 'Missing generated output claims: tests/generated',
    },
    {
      name: 'unexpected',
      claims: [...externalClaims(), { target: 'src/runtime.ts', kind: 'file' as const }],
      message: 'claimed unexpected generated target: src/runtime.ts',
    },
    {
      name: 'duplicate',
      claims: [...externalClaims(), { target: 'llms.txt', kind: 'file' as const }],
      message: 'Duplicate generated output claim: llms.txt',
    },
  ])('rejects $name output claims before replacement', async ({ claims, message }) => {
    const fixture = await makeFixture();
    const options = baseOptions(fixture);
    options.emitters = [
      outputEmitter(async (context) => {
        await writeExternalOutputs(context);
        return claims;
      }),
    ];

    await expect(orchestrateGeneration(options)).rejects.toThrow(message);
    await expectPriorOutputs(fixture);
    await expectNoTransactionDebris(fixture);
  });

  it('rejects a claim whose staged output is absent', async () => {
    const fixture = await makeFixture();
    const options = baseOptions(fixture);
    options.emitters = [
      outputEmitter(async (context) => {
        await writeExternalOutputs(context, 'examples/generated');
        return externalClaims();
      }),
    ];

    await expect(orchestrateGeneration(options)).rejects.toThrow(
      'Claimed generated output is missing: examples/generated',
    );
    await expectPriorOutputs(fixture);
    await expectNoTransactionDebris(fixture);
  });

  it('validates the maintained facade catalog before replacing generated output', async () => {
    const fixture = await makeFixture();
    const facadeCatalogPath = join(fixture.projectRoot, 'naming-overrides.json');
    await writeFile(
      facadeCatalogPath,
      `${JSON.stringify({
        schemaVersion: 2,
        operations: [
          {
            operationId: 'removed_operation',
            domain: 'items',
            method: 'getItem',
            reviewed: true,
          },
        ],
      })}\n`,
    );

    await expect(
      orchestrateGeneration({
        ...baseOptions(fixture),
        operationMetadata: {
          facadeCatalogPath,
          safetyOverridesPath: fixture.safetyOverridesPath,
        },
      }),
    ).rejects.toThrow('Stale facade catalog entry: removed_operation');
    await expectPriorOutputs(fixture);
    await expectNoTransactionDebris(fixture);
  });

  it.each([
    {
      name: 'missing',
      operations: [],
      message: 'Missing facade catalog entries: after_operation',
    },
    {
      name: 'unreviewed',
      operations: [
        {
          operationId: 'after_operation',
          domain: 'after',
          method: 'afterOperation',
          reviewed: false,
        },
      ],
      message: 'Facade catalog entry is not reviewed: after_operation',
    },
  ])(
    'does not use a production naming fallback for a $name entry',
    async ({ operations, message }) => {
      const fixture = await makeFixture();
      const facadeCatalogPath = join(fixture.projectRoot, 'naming-overrides.json');
      await writeFile(facadeCatalogPath, `${JSON.stringify({ schemaVersion: 2, operations })}\n`);

      await expect(
        orchestrateGeneration({
          ...baseOptions(fixture),
          operationMetadata: {
            facadeCatalogPath,
            safetyOverridesPath: fixture.safetyOverridesPath,
          },
        }),
      ).rejects.toThrow(message);
      await expectPriorOutputs(fixture);
      await expectNoTransactionDebris(fixture);
    },
  );
});

function baseOptions(fixture: Fixture): OrchestrateGenerationOptions {
  return {
    projectRoot: fixture.projectRoot,
    temporaryRoot: fixture.temporaryRoot,
    corrections: { manifestPath: fixture.correctionManifestPath },
    operationMetadata: {
      facadeCatalogPath: fixture.facadeCatalogPath,
      safetyOverridesPath: fixture.safetyOverridesPath,
    },
    emitters: [
      outputEmitter(async (context) => {
        await writeExternalOutputs(context);
        return externalClaims();
      }),
    ],
    openapi: {
      requestedDate: '2026-08-18',
      specificationUrl: 'https://example.test/openapi.json',
      fetchImplementation: async () => new Response(JSON.stringify(openApiDocument)),
    },
  };
}

function outputEmitter(
  emit: (context: EmitterContext) => Promise<readonly GeneratedOutputClaim[]>,
): GeneratedOutputEmitter {
  return { name: 'test-outputs', emit };
}

function externalClaims(): GeneratedOutputClaim[] {
  return generatedReplacementTargets
    .filter((target) => target !== 'openapi/generated')
    .map((target) => ({ target, kind: fileTargets.has(target) ? 'file' : 'directory' }));
}

async function writeExternalOutputs(
  context: EmitterContext,
  omittedTarget?: string,
): Promise<void> {
  for (const claim of externalClaims()) {
    if (claim.target === omittedTarget) continue;
    const path = context.outputPath(claim.target);
    if (claim.kind === 'file') {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, `new ${claim.target}\n`);
    } else {
      await mkdir(path, { recursive: true });
      await writeFile(join(path, 'generated.txt'), `new ${claim.target}\n`);
    }
  }
}

interface Fixture {
  readonly correctionManifestPath: string;
  readonly facadeCatalogPath: string;
  readonly projectRoot: string;
  readonly safetyOverridesPath: string;
  readonly temporaryRoot: string;
}

async function makeFixture(): Promise<Fixture> {
  const root = await makeTemporaryDirectory('esi-client-orchestration-test-');
  const projectRoot = join(root, 'project');
  const temporaryRoot = join(root, 'temporary');
  await Promise.all([
    mkdir(projectRoot, { recursive: true }),
    mkdir(temporaryRoot, { recursive: true }),
  ]);
  const correctionManifestPath = await writeCorrectionManifest(projectRoot);
  const facadeCatalogPath = join(root, 'facade-catalog.json');
  const safetyOverridesPath = join(root, 'empty-safety-overrides.json');
  await Promise.all([
    writeFile(
      facadeCatalogPath,
      `${JSON.stringify({
        schemaVersion: 2,
        operations: [
          {
            operationId: 'after_operation',
            domain: 'after',
            method: 'afterOperation',
            reviewed: true,
          },
        ],
      })}\n`,
    ),
    writeFile(safetyOverridesPath, `${JSON.stringify({ schemaVersion: 1, overrides: [] })}\n`),
  ]);
  for (const target of generatedReplacementTargets) {
    const path = join(projectRoot, target);
    if (fileTargets.has(target)) {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, `prior ${target}\n`);
    } else {
      await mkdir(path, { recursive: true });
      await writeFile(join(path, 'prior.txt'), `prior ${target}\n`);
    }
  }
  await Promise.all([
    writeFile(join(projectRoot, 'src/runtime.ts'), 'maintained runtime\n'),
    mkdir(join(projectRoot, 'scripts/generate'), { recursive: true }).then(() =>
      writeFile(join(projectRoot, 'scripts/generate/maintained.mjs'), 'maintained generator\n'),
    ),
    writeFile(join(projectRoot, 'tests/maintained.test.ts'), 'maintained test\n'),
  ]);
  return {
    correctionManifestPath,
    facadeCatalogPath,
    projectRoot,
    safetyOverridesPath,
    temporaryRoot,
  };
}

async function writeCorrectionManifest(
  directory: string,
  expectedTitle = 'Before correction',
): Promise<string> {
  const correctionDirectory = join(directory, 'corrections');
  await mkdir(correctionDirectory, { recursive: true });
  await writeFile(
    join(correctionDirectory, 'title.json'),
    `${JSON.stringify([
      { op: 'test', path: '/info/title', value: expectedTitle },
      { op: 'replace', path: '/info/title', value: 'After correction' },
      { op: 'test', path: '/paths/~1items/get/operationId', value: 'before_operation' },
      { op: 'replace', path: '/paths/~1items/get/operationId', value: 'after_operation' },
    ])}\n`,
  );
  const manifestPath = join(correctionDirectory, 'manifest.json');
  await writeFile(
    manifestPath,
    `${JSON.stringify({
      schemaVersion: 1,
      corrections: [
        {
          id: 'correct-title',
          patch: 'title.json',
          reason: 'Correct the fixture title.',
          from: '2026-01-01',
          through: '2026-12-31',
        },
      ],
    })}\n`,
  );
  return manifestPath;
}

async function snapshotGeneratedOutputs(projectRoot: string): Promise<Record<string, string>> {
  const snapshot: Record<string, string> = {};
  for (const target of generatedReplacementTargets) {
    const path = join(projectRoot, target);
    if (fileTargets.has(target)) {
      snapshot[target] = await readFile(path, 'base64');
    } else {
      await snapshotDirectory(path, target, snapshot);
    }
  }
  return snapshot;
}

async function snapshotDirectory(
  directory: string,
  relativeDirectory: string,
  snapshot: Record<string, string>,
): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(directory, entry.name);
    const relativePath = join(relativeDirectory, entry.name);
    if (entry.isDirectory()) await snapshotDirectory(path, relativePath, snapshot);
    else snapshot[relativePath] = await readFile(path, 'base64');
  }
}

async function expectPriorOutputs(fixture: Fixture): Promise<void> {
  const outputs = await Promise.all(
    generatedReplacementTargets.map(async (target) => {
      const path = join(fixture.projectRoot, target);
      const content = await readFile(
        fileTargets.has(target) ? path : join(path, 'prior.txt'),
        'utf8',
      );
      return [target, content];
    }),
  );
  expect(Object.fromEntries(outputs)).toEqual(
    Object.fromEntries(generatedReplacementTargets.map((target) => [target, `prior ${target}\n`])),
  );
}

async function expectMaintainedFiles(fixture: Fixture): Promise<void> {
  await expect(readFile(join(fixture.projectRoot, 'src/runtime.ts'), 'utf8')).resolves.toBe(
    'maintained runtime\n',
  );
  await expect(
    readFile(join(fixture.projectRoot, 'scripts/generate/maintained.mjs'), 'utf8'),
  ).resolves.toBe('maintained generator\n');
  await expect(
    readFile(join(fixture.projectRoot, 'tests/maintained.test.ts'), 'utf8'),
  ).resolves.toBe('maintained test\n');
}

async function expectNoTransactionDebris(fixture: Fixture): Promise<void> {
  await expect(readdir(fixture.temporaryRoot)).resolves.toEqual([]);
  const projectEntries = await readdir(fixture.projectRoot, { recursive: true });
  expect(projectEntries.filter((path) => path.includes('.esi-client-'))).toEqual([]);
}
