import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    root: 'src/index.ts',
    'operations/index': 'src/operations.ts',
    schemas: 'src/generated/schemas/index.ts',
    'domains/access-list': 'src/generated/domains/access-list.ts',
    'domains/activities': 'src/generated/domains/activities.ts',
    'domains/alliance': 'src/generated/domains/alliance.ts',
    'domains/assets': 'src/generated/domains/assets.ts',
    'domains/calendar': 'src/generated/domains/calendar.ts',
    'domains/character': 'src/generated/domains/character.ts',
    'domains/clones': 'src/generated/domains/clones.ts',
    'domains/contacts': 'src/generated/domains/contacts.ts',
    'domains/contracts': 'src/generated/domains/contracts.ts',
    'domains/corporation-projects': 'src/generated/domains/corporation-projects.ts',
    'domains/corporation': 'src/generated/domains/corporation.ts',
    'domains/cosmetics': 'src/generated/domains/cosmetics.ts',
    'domains/dogma': 'src/generated/domains/dogma.ts',
    'domains/faction-warfare': 'src/generated/domains/faction-warfare.ts',
    'domains/fittings': 'src/generated/domains/fittings.ts',
    'domains/fleets': 'src/generated/domains/fleets.ts',
    'domains/freelance-jobs': 'src/generated/domains/freelance-jobs.ts',
    'domains/incursions': 'src/generated/domains/incursions.ts',
    'domains/industry': 'src/generated/domains/industry.ts',
    'domains/insurance': 'src/generated/domains/insurance.ts',
    'domains/killmails': 'src/generated/domains/killmails.ts',
    'domains/location': 'src/generated/domains/location.ts',
    'domains/loyalty': 'src/generated/domains/loyalty.ts',
    'domains/mail': 'src/generated/domains/mail.ts',
    'domains/market': 'src/generated/domains/market.ts',
    'domains/meta': 'src/generated/domains/meta.ts',
    'domains/military-campaigns': 'src/generated/domains/military-campaigns.ts',
    'domains/paragon-hub': 'src/generated/domains/paragon-hub.ts',
    'domains/planetary-interaction': 'src/generated/domains/planetary-interaction.ts',
    'domains/routes': 'src/generated/domains/routes.ts',
    'domains/search': 'src/generated/domains/search.ts',
    'domains/skills': 'src/generated/domains/skills.ts',
    'domains/sovereignty': 'src/generated/domains/sovereignty.ts',
    'domains/status': 'src/generated/domains/status.ts',
    'domains/structures': 'src/generated/domains/structures.ts',
    'domains/universe': 'src/generated/domains/universe.ts',
    'domains/user-interface': 'src/generated/domains/user-interface.ts',
    'domains/wallet': 'src/generated/domains/wallet.ts',
    'domains/wars': 'src/generated/domains/wars.ts',
  },
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  clean: true,
  minify: false,
  sourcemap: false,
  hash: false,
  dts: {
    sourcemap: false,
  },
  deps: {
    neverBundle: true,
    onlyImport: ['zod'],
  },
  onSuccess: 'node scripts/check-runtime-imports.mjs',
});
