import type { PlatformModuleManifest } from '@eve-space/platform-module-contract/manifest'

const manifest = {
  id: 'member-audit',
  icon: 'corporation',
  defaultEnabled: false,
  sections: [
    { id: 'overview', kind: 'workspace', defaultEnabled: false },
    { id: 'skills', kind: 'sensitive-evidence', defaultEnabled: false, disclosureRevision: 1 },
    { id: 'assets', kind: 'sensitive-evidence', defaultEnabled: false, disclosureRevision: 1 },
    { id: 'wallet', kind: 'sensitive-evidence', defaultEnabled: false, disclosureRevision: 1 },
    { id: 'mail', kind: 'sensitive-evidence', defaultEnabled: false, disclosureRevision: 1 },
    { id: 'access-management', kind: 'access-management', defaultEnabled: false },
  ],
  server: {
    package: '@eve-space/member-audit-server',
    routes: [
      {
        id: 'member-search',
        namespace: '/member-audit/search',
        exportName: 'memberSearchRoutes',
        authorization: 'authenticated-session',
        audience: 'hr',
        requiredPermission: 'member-audit.search',
        additionalRequiredPermissions: ['member-audit.summary.read'],
        sectionId: 'overview',
        target: 'managed-organization-account-search',
        exposure: 'standard',
        persistenceOperations: [],
      },
      {
        id: 'member-summary',
        namespace: '/member-audit/accounts/:userId/summary',
        exportName: 'memberSummaryRoutes',
        authorization: 'authenticated-session',
        audience: 'hr',
        requiredPermission: 'member-audit.summary.read',
        sectionId: 'overview',
        target: 'managed-organization-account',
        exposure: 'standard',
        persistenceOperations: [],
      },
      {
        id: 'skills-detail',
        namespace: '/member-audit/accounts/:userId/characters/:characterId/skills',
        exportName: 'memberSkillsRoutes',
        authorization: 'authenticated-session',
        audience: 'hr',
        requiredPermission: 'member-audit.skills.read',
        sectionId: 'skills',
        target: 'managed-organization-character',
        exposure: 'sensitive-evidence',
        reviewerEvidenceResourceId: 'trained-skills',
        persistenceOperations: [{ operationId: 'read-skill-evidence' }],
      },
      {
        id: 'assets-detail',
        namespace: '/member-audit/accounts/:userId/characters/:characterId/assets',
        exportName: 'memberAssetsRoutes',
        authorization: 'authenticated-session',
        audience: 'hr',
        requiredPermission: 'member-audit.assets.read',
        sectionId: 'assets',
        target: 'managed-organization-character',
        exposure: 'sensitive-evidence',
        reviewerEvidenceResourceId: 'assets',
        persistenceOperations: [{ operationId: 'read-asset-evidence' }],
      },
      {
        id: 'wallet-detail',
        namespace: '/member-audit/accounts/:userId/characters/:characterId/wallet',
        exportName: 'memberWalletRoutes',
        authorization: 'authenticated-session',
        audience: 'hr',
        requiredPermission: 'member-audit.wallet.read',
        sectionId: 'wallet',
        target: 'managed-organization-character',
        exposure: 'sensitive-evidence',
        reviewerEvidenceResourceId: 'wallet-balance',
        persistenceOperations: [{ operationId: 'read-wallet-evidence' }],
      },
      {
        id: 'mail-detail',
        namespace: '/member-audit/accounts/:userId/characters/:characterId/mail',
        exportName: 'memberMailRoutes',
        authorization: 'authenticated-session',
        audience: 'hr',
        requiredPermission: 'member-audit.mail.read',
        sectionId: 'mail',
        target: 'managed-organization-character',
        exposure: 'sensitive-evidence',
        reviewerEvidenceResourceId: 'mail-headers',
        persistenceOperations: [{ operationId: 'read-mail-evidence' }],
      },
    ],
    migrations: [
      { name: 'member-audit-001-baseline.sql' },
      { name: 'member-audit-002-evidence-storage.sql' },
      { name: 'member-audit-003-persistence-operations.sql' },
      { name: 'member-audit-004-purge-operation.sql' },
    ],
    persistenceOperations: [
      {
        id: 'write-skill-snapshot',
        method: 'writeSkillSnapshot',
        revision: 1,
        mode: 'write',
        exportName: 'writeSkillSnapshotOperation',
        migration: 'member-audit-001-baseline.sql',
      },
      {
        id: 'read-skill-evidence',
        method: 'readSkillEvidence',
        revision: 1,
        mode: 'read',
        exportName: 'readSkillEvidenceOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'read-asset-evidence',
        method: 'readAssetEvidence',
        revision: 1,
        mode: 'read',
        exportName: 'readAssetEvidenceOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'read-wallet-evidence',
        method: 'readWalletEvidence',
        revision: 1,
        mode: 'read',
        exportName: 'readWalletEvidenceOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'read-mail-evidence',
        method: 'readMailEvidence',
        revision: 1,
        mode: 'read',
        exportName: 'readMailEvidenceOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'materialize-current-snapshot',
        method: 'materializeCurrentSnapshot',
        revision: 1,
        mode: 'write',
        exportName: 'materializeCurrentSnapshotOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'read-evidence-continuation',
        method: 'readEvidenceContinuation',
        revision: 1,
        mode: 'read',
        exportName: 'readEvidenceContinuationOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'write-evidence-continuation',
        method: 'writeEvidenceContinuation',
        revision: 1,
        mode: 'write',
        exportName: 'writeEvidenceContinuationOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'promote-evidence-observation',
        method: 'promoteEvidenceObservation',
        revision: 1,
        mode: 'write',
        exportName: 'promoteEvidenceObservationOperation',
        migration: 'member-audit-003-persistence-operations.sql',
      },
      {
        id: 'purge-evidence',
        method: 'purgeEvidence',
        revision: 1,
        mode: 'write',
        exportName: 'purgeEvidenceOperation',
        migration: 'member-audit-004-purge-operation.sql',
      },
    ],
    resources: [
      {
        id: 'trained-skills',
        operationId: 'skills',
        dependentOperationIds: [],
        coreDataProducts: ['published-skill-catalogue'],
        sectionId: 'skills',
        subjectKind: 'character',
        materializationIntervalSeconds: 3600,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [],
          materialization: [
            { operationId: 'write-skill-snapshot' },
            { operationId: 'materialize-current-snapshot' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'trainedSkillsResource',
      },
      {
        id: 'skill-queue',
        operationId: 'skill-queue',
        dependentOperationIds: [],
        coreDataProducts: ['published-skill-catalogue'],
        sectionId: 'skills',
        subjectKind: 'character',
        materializationIntervalSeconds: 900,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [],
          materialization: [
            { operationId: 'write-skill-snapshot' },
            { operationId: 'materialize-current-snapshot' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'skillQueueResource',
      },
      {
        id: 'assets',
        scheduled: false,
        operationId: 'character-assets-page',
        dependentOperationIds: ['character-asset-names', 'universe-resolve-names'],
        coreDataProducts: ['published-type-details', 'static-location-labels'],
        sectionId: 'assets',
        subjectKind: 'character',
        materializationIntervalSeconds: 3600,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [{ operationId: 'read-evidence-continuation' }],
          materialization: [
            { operationId: 'write-evidence-continuation' },
            { operationId: 'promote-evidence-observation' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'assetsResource',
      },
      {
        id: 'wallet-balance',
        scheduled: false,
        operationId: 'wallet-balance',
        dependentOperationIds: [],
        coreDataProducts: [],
        sectionId: 'wallet',
        subjectKind: 'character',
        materializationIntervalSeconds: 900,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [],
          materialization: [
            { operationId: 'materialize-current-snapshot' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'walletBalanceResource',
      },
      {
        id: 'wallet-journal',
        scheduled: false,
        operationId: 'wallet-journal',
        dependentOperationIds: [],
        coreDataProducts: [],
        sectionId: 'wallet',
        subjectKind: 'character',
        materializationIntervalSeconds: 900,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [{ operationId: 'read-evidence-continuation' }],
          materialization: [
            { operationId: 'write-evidence-continuation' },
            { operationId: 'promote-evidence-observation' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'walletJournalResource',
      },
      {
        id: 'wallet-transactions',
        scheduled: false,
        operationId: 'wallet-transactions',
        dependentOperationIds: [],
        coreDataProducts: [],
        sectionId: 'wallet',
        subjectKind: 'character',
        materializationIntervalSeconds: 900,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [{ operationId: 'read-evidence-continuation' }],
          materialization: [
            { operationId: 'write-evidence-continuation' },
            { operationId: 'promote-evidence-observation' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'walletTransactionsResource',
      },
      {
        id: 'mail-headers',
        scheduled: false,
        operationId: 'mail-headers',
        dependentOperationIds: ['mail-lists', 'universe-resolve-names'],
        coreDataProducts: [],
        sectionId: 'mail',
        subjectKind: 'character',
        materializationIntervalSeconds: 900,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [{ operationId: 'read-evidence-continuation' }],
          materialization: [
            { operationId: 'write-evidence-continuation' },
            { operationId: 'promote-evidence-observation' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'mailHeadersResource',
      },
      {
        id: 'mail-details',
        scheduled: false,
        operationId: 'mail-message',
        dependentOperationIds: ['mail-lists', 'universe-resolve-names'],
        coreDataProducts: [],
        sectionId: 'mail',
        subjectKind: 'character',
        materializationIntervalSeconds: 900,
        eligibility: { kind: 'current-managed-member-character' },
        persistence: {
          projection: [{ operationId: 'read-evidence-continuation' }],
          materialization: [
            { operationId: 'write-evidence-continuation' },
            { operationId: 'promote-evidence-observation' },
            { operationId: 'purge-evidence' },
          ],
        },
        exportName: 'mailDetailsResource',
      },
    ],
    esiOperations: [],
    activityProviders: [],
  },
  nuxt: {
    package: '@eve-space/member-audit-nuxt',
    pages: [],
    navigation: [],
  },
} satisfies PlatformModuleManifest

export default manifest
