const moduleSpecifierPattern = /^\.\/[A-Za-z0-9_./-]+\.js$/u;

export function createProvenanceHeader(provenance, format) {
  validateProvenance(provenance);
  const lines = [
    '@generated by @evespace/esi-client.',
    `Compatibility date: ${provenance.compatibilityDate}.`,
    `Specification SHA-256: ${provenance.sha256}.`,
    'DO NOT EDIT.',
  ];
  if (format === 'typescript' || format === 'json-compatible') {
    return `${lines.map((line) => `// ${line}`).join('\n')}\n`;
  }
  if (format === 'markdown') return `<!--\n${lines.join('\n')}\n-->\n`;
  throw new Error(`Unsupported provenance header format: ${String(format)}`);
}

export function renderGeneratedBarrel(moduleSpecifiers, provenance) {
  if (!Array.isArray(moduleSpecifiers)) {
    throw new Error('Generated barrel module specifiers must be an array');
  }
  const seen = new Set();
  for (const specifier of moduleSpecifiers) {
    if (
      typeof specifier !== 'string' ||
      !moduleSpecifierPattern.test(specifier) ||
      specifier.split('/').includes('..')
    ) {
      throw new Error(`Invalid generated barrel module specifier: ${String(specifier)}`);
    }
    if (seen.has(specifier)) {
      throw new Error(`Duplicate generated barrel module specifier: ${specifier}`);
    }
    seen.add(specifier);
  }
  const exports = [...seen]
    .toSorted(compareText)
    .map((specifier) => `export * from '${specifier}';`)
    .join('\n');
  return `${createProvenanceHeader(provenance, 'typescript')}\n${exports}${exports ? '\n' : ''}`;
}

export function createOperationAccountingReport(model, operationMetadata) {
  const metadataById = new Map();
  for (const metadata of operationMetadata) {
    if (metadataById.has(metadata.operationId)) {
      throw new Error(`Duplicate operation metadata: ${metadata.operationId}`);
    }
    metadataById.set(metadata.operationId, metadata);
  }

  const sourceIds = new Set(model.accounting.sourceOperationIds);
  const generatedIds = new Set(model.accounting.normalizedOperationIds);
  const accountedExcludedIds = new Set(model.accounting.excludedOperationIds);
  const excludedById = new Map(
    model.exclusions.map((exclusion) => [exclusion.operationId, exclusion]),
  );
  if (sourceIds.size !== model.accounting.sourceOperationIds.length) {
    throw new Error('Operation accounting contains duplicate source operation IDs');
  }
  if (generatedIds.size !== model.accounting.normalizedOperationIds.length) {
    throw new Error('Operation accounting contains duplicate generated operation IDs');
  }
  if (accountedExcludedIds.size !== model.accounting.excludedOperationIds.length) {
    throw new Error('Operation accounting contains duplicate excluded operation IDs');
  }
  if (excludedById.size !== model.exclusions.length) {
    throw new Error('Operation exclusions contain duplicate operation IDs');
  }
  const modelOperationIds = new Set(model.operations.map(({ operationId }) => operationId));
  if (
    modelOperationIds.size !== generatedIds.size ||
    [...modelOperationIds].some((operationId) => !generatedIds.has(operationId))
  ) {
    throw new Error('Normalized operations do not match generated operation accounting');
  }
  if (
    accountedExcludedIds.size !== excludedById.size ||
    [...accountedExcludedIds].some((operationId) => !excludedById.has(operationId))
  ) {
    throw new Error('Operation exclusions do not match excluded operation accounting');
  }
  for (const operationId of sourceIds) {
    const generated = generatedIds.has(operationId);
    const excluded = excludedById.has(operationId);
    if (generated === excluded) {
      throw new Error(`Operation accounting must classify exactly once: ${operationId}`);
    }
  }
  for (const operationId of [...generatedIds, ...excludedById.keys()]) {
    if (!sourceIds.has(operationId))
      throw new Error(`Operation accounting contains stale ID: ${operationId}`);
  }
  if (metadataById.size !== generatedIds.size) {
    throw new Error('Operation metadata does not cover every generated operation');
  }

  const operations = [...sourceIds].toSorted(compareText).map((operationId) => {
    const exclusion = excludedById.get(operationId);
    if (exclusion !== undefined) {
      return {
        operationId,
        reason: exclusion.reason,
        status: 'excluded',
      };
    }
    const metadata = metadataById.get(operationId);
    if (metadata === undefined || !generatedIds.has(operationId)) {
      throw new Error(`Missing operation metadata: ${operationId}`);
    }
    return {
      classification: metadata.classification,
      facade: { domain: metadata.domain, method: metadata.method },
      operationId,
      status: 'generated',
    };
  });

  return deepFreeze({
    operations,
    schemaVersion: 1,
    summary: {
      excluded: excludedById.size,
      generated: generatedIds.size,
      source: sourceIds.size,
    },
  });
}

export function renderGeneratedJson(value, provenance) {
  validateProvenance(provenance);
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Generated JSON root must be an object');
  }
  if (Object.hasOwn(value, '_generated')) {
    throw new Error('Generated JSON value reserves the _generated field');
  }
  return serializeJson({
    ...createJsonProvenanceHeader(provenance),
    ...value,
  });
}

export function createJsonProvenanceHeader(provenance) {
  validateProvenance(provenance);
  return deepFreeze({
    _generated: {
      compatibilityDate: provenance.compatibilityDate,
      notice: 'Generated by @evespace/esi-client. DO NOT EDIT.',
      specificationSha256: provenance.sha256,
    },
  });
}

function validateProvenance(provenance) {
  if (
    provenance === null ||
    typeof provenance !== 'object' ||
    typeof provenance.compatibilityDate !== 'string' ||
    !/^\d{4}-\d{2}-\d{2}$/u.test(provenance.compatibilityDate) ||
    typeof provenance.sha256 !== 'string' ||
    !/^[a-f0-9]{64}$/u.test(provenance.sha256)
  ) {
    throw new Error('Invalid generation provenance');
  }
}

function serializeJson(value) {
  return `${JSON.stringify(sortJsonValue(value), null, 2)}\n`;
}

function sortJsonValue(value) {
  if (Array.isArray(value)) return value.map(sortJsonValue);
  if (value === null || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .toSorted(([left], [right]) => compareText(left, right))
      .map(([key, entry]) => [key, sortJsonValue(entry)]),
  );
}

function compareText(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function deepFreeze(value) {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const entry of Object.values(value)) deepFreeze(entry);
  }
  return value;
}
