import type { JsonObject, NormalizedOpenApiModel } from './normalize.ts';
import type {
  OperationSafetyClassification,
  ResolvedOperationMetadata,
} from './operation-metadata.ts';

export type ProvenanceHeaderFormat = 'typescript' | 'markdown' | 'json-compatible';

export interface ArtifactProvenance {
  readonly compatibilityDate: string;
  readonly sha256: string;
}

export interface JsonProvenanceHeader {
  readonly _generated: {
    readonly compatibilityDate: string;
    readonly notice: string;
    readonly specificationSha256: string;
  };
}

export interface GeneratedOperationAccountingEntry {
  readonly operationId: string;
  readonly status: 'generated';
  readonly classification: OperationSafetyClassification;
  readonly facade: {
    readonly domain: string;
    readonly method: string;
  };
}

export interface ExcludedOperationAccountingEntry {
  readonly operationId: string;
  readonly status: 'excluded';
  readonly reason: {
    readonly code: string;
    readonly detail: string;
  };
}

export interface OperationAccountingReport {
  readonly schemaVersion: 1;
  readonly summary: {
    readonly source: number;
    readonly generated: number;
    readonly excluded: number;
  };
  readonly operations: readonly (
    | GeneratedOperationAccountingEntry
    | ExcludedOperationAccountingEntry
  )[];
}

interface OperationAccountingEntryMetadata {
  readonly domain: string;
  readonly method: string;
  readonly classification: OperationSafetyClassification;
}

const moduleSpecifierPattern = /^\.\/[A-Za-z0-9_./-]+\.js$/u;

export function createProvenanceHeader(
  provenance: ArtifactProvenance,
  format: ProvenanceHeaderFormat,
): string {
  validateProvenance(provenance);
  const lines = [
    '@generated by @evespace/esi-client.',
    `Compatibility date: ${provenance.compatibilityDate}.`,
    `Specification SHA-256: ${provenance.sha256}.`,
    'DO NOT EDIT.',
  ];
  if (format === 'typescript' || format === 'json-compatible') {
    const comment = lines.map((line) => `// ${line}`).join('\n');
    return `${comment}\n`;
  }
  if (format === 'markdown') return `<!--\n${lines.join('\n')}\n-->\n`;
  throw new Error(`Unsupported provenance header format: ${String(format)}`);
}

export function renderGeneratedBarrel(
  moduleSpecifiers: readonly string[],
  provenance: ArtifactProvenance,
): string {
  if (!Array.isArray(moduleSpecifiers)) {
    throw new TypeError('Generated barrel module specifiers must be an array');
  }
  const seen = new Set<string>();
  for (const specifier of moduleSpecifiers) {
    if (
      typeof specifier !== 'string' ||
      !moduleSpecifierPattern.test(specifier) ||
      specifier.split('/').includes('..')
    ) {
      throw new Error(`Invalid generated barrel module specifier: ${String(specifier)}`);
    }
    if (seen.has(specifier)) {
      throw new Error(`Duplicate generated barrel module specifier: ${specifier}`);
    }
    seen.add(specifier);
  }
  const exports = [...seen]
    .toSorted(compareText)
    .map((specifier) => `export * from '${specifier}';`)
    .join('\n');
  return `${createProvenanceHeader(provenance, 'typescript')}\n${exports}${exports ? '\n' : ''}`;
}

export function createOperationAccountingReport(
  model: NormalizedOpenApiModel,
  operationMetadata: readonly ResolvedOperationMetadata[],
): OperationAccountingReport {
  const metadataById = indexOperationMetadata(operationMetadata);
  const sourceIds = new Set(model.accounting.sourceOperationIds);
  const generatedIds = new Set(model.accounting.normalizedOperationIds);
  const accountedExcludedIds = new Set(model.accounting.excludedOperationIds);
  const excludedById = new Map(
    model.exclusions.map((exclusion) => [exclusion.operationId, exclusion]),
  );
  validateOperationAccountingSets(
    model,
    sourceIds,
    generatedIds,
    accountedExcludedIds,
    excludedById,
  );
  validateOperationClassifications(sourceIds, generatedIds, excludedById);
  validateOperationMetadataCoverage(metadataById, generatedIds);

  const operations = [...sourceIds]
    .toSorted(compareText)
    .map((operationId) =>
      createOperationAccountingEntry(operationId, generatedIds, excludedById, metadataById),
    );

  return deepFreeze({
    operations,
    schemaVersion: 1 as const,
    summary: {
      excluded: excludedById.size,
      generated: generatedIds.size,
      source: sourceIds.size,
    },
  });
}

function indexOperationMetadata(
  operationMetadata: readonly ResolvedOperationMetadata[],
): Map<string, OperationAccountingEntryMetadata> {
  const metadataById = new Map<string, OperationAccountingEntryMetadata>();
  for (const metadata of operationMetadata) {
    if (metadataById.has(metadata.operationId)) {
      throw new Error(`Duplicate operation metadata: ${metadata.operationId}`);
    }
    metadataById.set(metadata.operationId, metadata);
  }
  return metadataById;
}

function validateOperationAccountingSets(
  model: NormalizedOpenApiModel,
  sourceIds: ReadonlySet<string>,
  generatedIds: ReadonlySet<string>,
  accountedExcludedIds: ReadonlySet<string>,
  excludedById: Map<string, NormalizedOpenApiModel['exclusions'][number]>,
): void {
  if (sourceIds.size !== model.accounting.sourceOperationIds.length) {
    throw new Error('Operation accounting contains duplicate source operation IDs');
  }
  if (generatedIds.size !== model.accounting.normalizedOperationIds.length) {
    throw new Error('Operation accounting contains duplicate generated operation IDs');
  }
  if (accountedExcludedIds.size !== model.accounting.excludedOperationIds.length) {
    throw new Error('Operation accounting contains duplicate excluded operation IDs');
  }
  if (excludedById.size !== model.exclusions.length) {
    throw new Error('Operation exclusions contain duplicate operation IDs');
  }
  const modelOperationIds = new Set(model.operations.map(({ operationId }) => operationId));
  if (
    modelOperationIds.size !== generatedIds.size ||
    [...modelOperationIds].some((operationId) => !generatedIds.has(operationId))
  ) {
    throw new Error('Normalized operations do not match generated operation accounting');
  }
  if (
    accountedExcludedIds.size !== excludedById.size ||
    [...accountedExcludedIds].some((operationId) => !excludedById.has(operationId))
  ) {
    throw new Error('Operation exclusions do not match excluded operation accounting');
  }
}

function validateOperationClassifications(
  sourceIds: ReadonlySet<string>,
  generatedIds: ReadonlySet<string>,
  excludedById: ReadonlyMap<string, unknown>,
): void {
  for (const operationId of sourceIds) {
    const generated = generatedIds.has(operationId);
    const excluded = excludedById.has(operationId);
    if (generated === excluded) {
      throw new Error(`Operation accounting must classify exactly once: ${operationId}`);
    }
  }
  for (const operationId of [...generatedIds, ...excludedById.keys()]) {
    if (!sourceIds.has(operationId))
      throw new Error(`Operation accounting contains stale ID: ${operationId}`);
  }
}

function validateOperationMetadataCoverage(
  metadataById: ReadonlyMap<string, unknown>,
  generatedIds: ReadonlySet<string>,
): void {
  if (metadataById.size !== generatedIds.size) {
    throw new Error('Operation metadata does not cover every generated operation');
  }
}

function createOperationAccountingEntry(
  operationId: string,
  generatedIds: ReadonlySet<string>,
  excludedById: ReadonlyMap<string, NormalizedOpenApiModel['exclusions'][number]>,
  metadataById: ReadonlyMap<string, OperationAccountingEntryMetadata>,
): GeneratedOperationAccountingEntry | ExcludedOperationAccountingEntry {
  const exclusion = excludedById.get(operationId);
  if (exclusion !== undefined) {
    return {
      operationId,
      reason: exclusion.reason,
      status: 'excluded',
    };
  }
  const metadata = metadataById.get(operationId);
  if (metadata === undefined || !generatedIds.has(operationId)) {
    throw new Error(`Missing operation metadata: ${operationId}`);
  }
  return {
    classification: metadata.classification,
    facade: { domain: metadata.domain, method: metadata.method },
    operationId,
    status: 'generated',
  };
}

export function renderGeneratedJson(
  value: JsonObject | OperationAccountingReport,
  provenance: ArtifactProvenance,
): string {
  validateProvenance(provenance);
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Generated JSON root must be an object');
  }
  if (Object.hasOwn(value, '_generated')) {
    throw new Error('Generated JSON value reserves the _generated field');
  }
  return serializeJson({
    ...createJsonProvenanceHeader(provenance),
    ...value,
  });
}

export function createJsonProvenanceHeader(provenance: ArtifactProvenance): JsonProvenanceHeader {
  validateProvenance(provenance);
  return deepFreeze({
    _generated: {
      compatibilityDate: provenance.compatibilityDate,
      notice: 'Generated by @evespace/esi-client. DO NOT EDIT.',
      specificationSha256: provenance.sha256,
    },
  });
}

function validateProvenance(provenance: ArtifactProvenance): void {
  if (
    provenance === null ||
    typeof provenance !== 'object' ||
    typeof provenance.compatibilityDate !== 'string' ||
    !/^\d{4}-\d{2}-\d{2}$/u.test(provenance.compatibilityDate) ||
    typeof provenance.sha256 !== 'string' ||
    !/^[a-f0-9]{64}$/u.test(provenance.sha256)
  ) {
    throw new Error('Invalid generation provenance');
  }
}

function serializeJson(value: Record<string, unknown>): string {
  return `${JSON.stringify(sortJsonValue(value), null, 2)}\n`;
}

function sortJsonValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortJsonValue);
  if (value === null || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .toSorted(([left], [right]) => compareText(left, right))
      .map(([key, entry]) => [key, sortJsonValue(entry)]),
  );
}

function compareText(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const entry of Object.values(value)) deepFreeze(entry);
  }
  return value;
}
