import { readFileSync } from 'node:fs'
import { dirname, relative, resolve, sep } from 'node:path'
import {
  readCompiledPlatformModules,
  type CompiledPlatformModules,
} from '@eve-space/platform-module-contract/compiler'
import type { PlatformModuleManifest } from '@eve-space/platform-module-contract/manifest'
import type {
  PlatformInstalledModuleDefinition,
  PlatformInstalledModuleMigrationDescriptor,
  PlatformInstalledModuleSectionDefinition,
  PlatformInstalledOrganizationAdmissionScopeDescriptor,
  PlatformInstalledReviewerContributionDescriptor,
} from '@eve-space/platform-module-contract/installed'
import type { PlatformInstalledActivityProviderDescriptor } from '@eve-space/platform-module-contract/activity'
import {
  platformNavigationPlacements,
  type PlatformInstalledNavigation,
  type PlatformNavigationDefault,
  type PlatformNuxtContributionDescriptor,
  type PlatformReviewerNuxtContribution,
} from '@eve-space/platform-module-contract/nuxt'
import {
  platformOrganizationAdmissionScope,
  resolvePlatformModuleRoutePath,
} from '@eve-space/platform-module-contract/server'
import {
  formatPlatformModuleConformanceReport,
  verifyInstalledModuleArtifacts,
} from '@eve-space/platform-module-conformance'
import {
  canonicalizePersistenceRoutineSql,
  type CanonicalPersistenceRoutine,
  createModulePersistenceContractFingerprint,
} from '@eve-space/platform-module-persistence-policy/persistence-policy'
import { coreNavigationDefaults } from './authorities.js'
import type { PlatformRegistryRenderer } from './renderer-interface.js'
import {
  resolveInstalledModuleReleases,
  type ResolvedInstalledModuleRelease,
  type ResolvedModulePackage,
} from './resolved-release.js'

export const generatedRegistryPaths = [
  'api/src/generated/platform/installed-module-routes.ts',
  'api/src/generated/platform/installed-module-activity-providers.ts',
  'api/src/generated/platform/installed-module-worker.ts',
  'api/src/generated/platform/installed-module-migrations.ts',
  'api/src/generated/platform/installed-module-esi.ts',
  'api/src/generated/platform/installed-module-persistence.ts',
  'api/src/generated/platform/installed-module-runtime.ts',
  'generated/platform/installed-nuxt-modules.ts',
  'generated/platform/installed-nuxt-contributions.ts',
  'generated/platform/installed-module-navigation.ts',
  'api/src/generated/platform/installed-module-inventory.ts',
  'api/src/generated/platform/installed-permission-catalog.ts',
  'api/src/generated/platform/installed-reviewer-contributions.ts',
  'api/src/generated/platform/installed-module-resource-declarations.ts',
] as const

interface ReviewedPersistenceRoutine extends CanonicalPersistenceRoutine {
  readonly migration: string
}

export interface InstalledModuleRegistryInput {
  readonly compiled: CompiledPlatformModules
  readonly persistenceRoutines: readonly ReviewedPersistenceRoutine[]
  readonly releases: readonly ResolvedInstalledModuleRelease[]
}

const generatedHeader =
  '// This file is generated by scripts/generate-module-registries.ts. Do not edit.\n\n'

export async function loadInstalledModuleManifests(root: string) {
  const { compiled, releases } = resolveInstalledModuleReleases(root)
  await Promise.all(releases.map(verifyReleaseArtifacts))
  const persistenceRoutines = await Promise.all(
    releases.flatMap((release) =>
      release.manifest.server.persistenceOperations.map(async (operation) => {
        const migration = release.migrations.find(({ name }) => name === operation.migration)
        if (!migration)
          throw new Error(
            `Missing resolved persistence migration ${release.moduleId}/${operation.migration}`,
          )
        const sql = readFileSync(migration.path, 'utf8')
        return {
          ...(await canonicalizePersistenceRoutineSql({
            moduleId: release.moduleId,
            operationId: operation.id,
            revision: operation.revision,
            mode: operation.mode,
            sql,
          })),
          migration: operation.migration,
        }
      }),
    ),
  )
  return { compiled, releases, persistenceRoutines } satisfies InstalledModuleRegistryInput
}

async function verifyReleaseArtifacts(release: ResolvedInstalledModuleRelease) {
  const result = await verifyInstalledModuleArtifacts(
    {
      manifest: {
        packageRoot: release.packages.manifest.root,
        export: release.manifestExport,
      },
      server: { packageRoot: release.packages.server.root },
      nuxt: { packageRoot: release.packages.nuxt.root },
    },
    {
      allowLocalDependencySpecifiers: {
        server: release.packages.server.workspace,
        nuxt: release.packages.nuxt.workspace,
      },
    },
  )
  if (!result.ok)
    throw new Error(
      `Module ${release.moduleId} artifact verification failed:\n${formatPlatformModuleConformanceReport(result)}`,
    )
}

export const generateRegistryFiles = function generateRegistryFiles(
  compiled: CompiledPlatformModules,
  persistenceRoutines: InstalledModuleRegistryInput['persistenceRoutines'] = [],
  releases: InstalledModuleRegistryInput['releases'] = [],
) {
  return new Map<string, string>([
    [generatedRegistryPaths[0], renderApiRoutes(compiled)],
    [generatedRegistryPaths[1], renderActivityProviders(compiled)],
    [generatedRegistryPaths[2], renderWorkerResources(compiled)],
    [generatedRegistryPaths[3], renderMigrations(compiled, releases)],
    [generatedRegistryPaths[4], renderEsiOperations(compiled)],
    [generatedRegistryPaths[5], renderPersistenceOperations(compiled, persistenceRoutines)],
    [generatedRegistryPaths[6], renderModuleRuntime(compiled)],
    [generatedRegistryPaths[7], renderNuxtModules(compiled)],
    [generatedRegistryPaths[8], renderNuxtContributions(compiled)],
    [generatedRegistryPaths[9], renderNavigation(compiled)],
    [generatedRegistryPaths[10], renderInstalledInventory(compiled, releases)],
    [generatedRegistryPaths[11], renderInstalledPermissionCatalog(compiled)],
    [generatedRegistryPaths[12], renderInstalledReviewerContributions(compiled)],
    [generatedRegistryPaths[13], renderResourceDeclarations(compiled)],
  ])
} satisfies PlatformRegistryRenderer

function renderApiRoutes(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const reviewerContributions = installedReviewerContributionDescriptors(manifests)
  const routes = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.routes.map((route, routeIndex) => ({
      manifest,
      route,
      binding: `module${moduleIndex}Route${routeIndex}`,
      reviewerContributionIndex: reviewerContributions.findIndex(
        (contribution) =>
          contribution.moduleId === manifest.id && contribution.routeId === route.id,
      ),
    })),
  )
  const imports = renderServerImports(
    routes.map(({ manifest, route, binding }) => ({
      packageName: manifest.server.package,
      exportName: route.exportName,
      localName: `${binding}Factory`,
    })),
  )
  const hasReviewerContributions = routes.some(
    ({ reviewerContributionIndex }) => reviewerContributionIndex >= 0,
  )
  const hasLegacyRoutes = routes.some(
    ({ reviewerContributionIndex }) => reviewerContributionIndex < 0,
  )
  const compositionImports = [
    ...(hasReviewerContributions ? ['composePlatformReviewerContributionRoute'] : []),
    ...(hasLegacyRoutes ? ['platformModuleRouteComposers'] : []),
  ]
  const capabilityImports = [
    ...(routes.some(
      ({ route, reviewerContributionIndex }) =>
        reviewerContributionIndex < 0 && (route.target === undefined || route.target === 'caller'),
    )
      ? ['createPlatformModuleRouteCapabilities']
      : []),
    ...(hasReviewerContributions ? ['createPlatformReviewerContributionRouteCapabilities'] : []),
    ...(routes.some(
      ({ route, reviewerContributionIndex }) =>
        reviewerContributionIndex < 0 && route.target !== undefined && route.target !== 'caller',
    )
      ? ['createPlatformReviewerContributionRouteCapabilities']
      : []),
  ]
  const platformImports = routes.length
    ? [
        `import { ${compositionImports.join(', ')} } from '../../platform/module-route-composition.js'`,
        `import { ${capabilityImports.join(', ')} } from '../../platform/module-route-capabilities.js'`,
        ...(hasReviewerContributions
          ? [
              "import { installedReviewerContributions } from './installed-reviewer-contributions.js'",
            ]
          : []),
      ].join('\n') + '\n'
    : ''
  const factories = routes.map(({ manifest, route, binding, reviewerContributionIndex }) => {
    let capabilities: string
    if (reviewerContributionIndex >= 0)
      capabilities = `createPlatformReviewerContributionRouteCapabilities(installedReviewerContributions[${reviewerContributionIndex}]!, ${JSON.stringify(route.coreDataProducts ?? [])} as const)`
    else if (route.target !== undefined && route.target !== 'caller')
      capabilities = `createPlatformReviewerContributionRouteCapabilities({ moduleId: ${quote(manifest.id)} }, ${JSON.stringify(route.coreDataProducts ?? [])} as const)`
    else
      capabilities = `createPlatformModuleRouteCapabilities(${quote(manifest.id)}, ${quote(route.id)}, ${JSON.stringify(route.coreDataProducts ?? [])} as const)`
    return `const ${binding} = ${binding}Factory(${capabilities})\n`
  })
  const chain = routes.map(({ manifest, route, binding, reviewerContributionIndex }) => {
    const composer =
      route.target !== undefined && route.target !== 'caller' ? route.target : route.authorization
    const section = route.sectionId ? `, sectionId: ${quote(route.sectionId)}` : ''
    const additionalPermissions = route.additionalRequiredPermissions
      ? `, additionalRequiredPermissions: ${JSON.stringify(route.additionalRequiredPermissions)} as const`
      : ''
    const target = route.target ? `, target: ${quote(route.target)}` : ''
    const exposure = route.exposure ? `, exposure: ${quote(route.exposure)}` : ''
    const reviewerEvidence = route.reviewerEvidenceResourceId
      ? `, reviewerEvidence: { routeId: ${quote(route.id)}, resourceId: ${quote(route.reviewerEvidenceResourceId)}, operationId: ${quote(route.persistenceOperations[0]!.operationId)} }`
      : ''
    const sectionDescriptor = manifest.sections?.find(({ id }) => id === route.sectionId)
    const sectionResourceIds =
      sectionDescriptor?.kind === 'workspace'
        ? manifest.server.resources.map(({ id }) => id)
        : manifest.server.resources
            .filter(({ sectionId }) => sectionId === route.sectionId)
            .map(({ id }) => id)
    const reviewerResourceIds =
      reviewerContributionIndex < 0
        ? ''
        : `, reviewerResourceIds: ${JSON.stringify(sectionResourceIds)} as const`
    const organizationCommands = route.organizationCommands
      ? `, organizationCommands: ${JSON.stringify(route.organizationCommands)} as const`
      : ''
    const contributionRoute =
      reviewerContributionIndex >= 0
        ? `, routeId: ${quote(route.id)}, namespace: ${quote(route.namespace)}`
        : ''
    const organization = `{ publisherPackage: ${quote(manifest.release.publisherPackage)}, moduleId: ${quote(manifest.id)}${contributionRoute}, audience: ${quote(route.audience)}, requiredPermission: ${quote(route.requiredPermission)}${additionalPermissions}${section}${target}${exposure}${reviewerEvidence}${reviewerResourceIds}${organizationCommands} }`
    if (reviewerContributionIndex >= 0)
      return `\n  .route(\n    ${quote(route.namespace)},\n    composePlatformReviewerContributionRoute(\n      installedReviewerContributions[${reviewerContributionIndex}]!,\n      ${organization},\n      ${binding},\n    ),\n  )`
    return `\n  .route(\n    ${quote(route.namespace)},\n    platformModuleRouteComposers[${quote(composer)}](\n      ${quote(manifest.id)},\n      { publisherPackage: ${quote(manifest.release.publisherPackage)}, moduleId: ${quote(manifest.id)}, audience: ${quote(route.audience)}, requiredPermission: ${quote(route.requiredPermission)}${additionalPermissions}${section}${target}${exposure}${reviewerEvidence}${organizationCommands} },\n      ${binding},\n    ),\n  )`
  })
  const composition = routes.length ? `${platformImports}${imports}\n${factories.join('')}\n` : '\n'
  return `${generatedHeader}import { Hono } from 'hono'\n${composition}export const installedModuleRoutes = new Hono()${chain.join('')}\n`
}

function renderActivityProviders(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const providers = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.activityProviders.map((provider, providerIndex) => ({
      manifest,
      provider,
      binding: `module${moduleIndex}ActivityProvider${providerIndex}`,
    })),
  )
  const imports = renderServerImports(
    providers.map(({ manifest, provider, binding }) => ({
      packageName: manifest.server.package,
      exportName: provider.exportName,
      localName: `${binding}Factory`,
    })),
  )
  const platformImport = providers.length
    ? "import { createPlatformModuleActivityProviderCapabilities } from '../../platform/module-activity-provider-capabilities.js'\n"
    : ''
  const descriptors: PlatformInstalledActivityProviderDescriptor[] = providers.map(
    ({ manifest, provider }) => ({
      publisherPackage: manifest.release.publisherPackage,
      moduleId: manifest.id,
      providerId: provider.id,
      sectionId: provider.sectionId,
      coreDataProducts: provider.coreDataProducts ?? [],
      audience: provider.audience,
      requiredPermission: provider.requiredPermission,
      freshness: provider.freshness,
      pageIds: manifest.nuxt.pages.map(({ id }) => id),
      persistenceOperations: provider.persistenceOperations,
      invoke: undefined as never,
    }),
  )
  const rendered = descriptors.length
    ? `[${descriptors
        .map((descriptor, index) => {
          const binding = providers[index]!.binding
          const sectionId = descriptor.sectionId
            ? ` sectionId: ${quote(descriptor.sectionId)},`
            : ''
          return `\n  { publisherPackage: ${quote(descriptor.publisherPackage)}, moduleId: ${quote(descriptor.moduleId)}, providerId: ${quote(descriptor.providerId)},${sectionId} coreDataProducts: ${JSON.stringify(descriptor.coreDataProducts)} as const, audience: ${quote(descriptor.audience)}, requiredPermission: ${quote(descriptor.requiredPermission)}, freshness: { staleAfterSeconds: ${descriptor.freshness.staleAfterSeconds} }, pageIds: [${descriptor.pageIds.map(quote).join(', ')}], persistenceOperations: ${JSON.stringify(descriptor.persistenceOperations)} as const, invoke: (context) => ${binding}Factory(createPlatformModuleActivityProviderCapabilities(${quote(descriptor.moduleId)}, ${quote(descriptor.providerId)}, context, ${JSON.stringify(descriptor.coreDataProducts)} as const, ${descriptor.sectionId ? quote(descriptor.sectionId) : 'undefined'}))(context) },`
        })
        .join('')}\n]`
    : '[]'
  return `${generatedHeader}import type { PlatformInstalledActivityProviderDescriptor } from '@eve-space/platform-module-contract/activity'\n${platformImport}${imports}\nexport const installedModuleActivityProviders =\n  ${rendered} as const satisfies readonly PlatformInstalledActivityProviderDescriptor[]\n`
}

function renderWorkerResources(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const resources = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.resources.map((resource, resourceIndex) => ({
      manifest,
      resource,
      binding: `module${moduleIndex}Resource${resourceIndex}`,
    })),
  )
  const imports = renderServerImports(
    resources.map(({ manifest, resource, binding }) => ({
      packageName: manifest.server.package,
      exportName: resource.exportName,
      localName: binding,
    })),
  )
  const descriptors = resources.map(({ manifest, resource, binding }) => {
    const coreDataProducts = JSON.stringify(resource.coreDataProducts ?? [])
    const capabilityKey = quote(`${manifest.id}/${resource.id}`)
    const batch = resource.batch
      ? ` batch: { mode: ${quote(resource.batch.mode)}, operationId: ${quote(resource.batch.operationId)} },`
      : ''
    const dependent = resource.dependentOperationIds?.length
      ? ` dependentOperationIds: ${JSON.stringify(resource.dependentOperationIds)},`
      : ''
    const sectionId = resource.sectionId ? ` sectionId: ${quote(resource.sectionId)},` : ''
    const scheduled = resource.scheduled === false ? ' scheduled: false,' : ''
    const protocolOperations = [
      ...new Set([resource.operationId, ...(resource.dependentOperationIds ?? [])]),
    ]
      .map(quote)
      .join(' | ')
    const contract = `PlatformResourceImplementationForContract<typeof ${binding}, ${quote(resource.operationId)}, PlatformEsiOperationProtocol<${protocolOperations}>, readonly ${coreDataProducts}, InstalledModuleResourceProjectionPersistence<${capabilityKey}>, InstalledModuleResourceMaterializationPersistence<${capabilityKey}>>`
    return `({ moduleId: ${quote(manifest.id)}, resourceId: ${quote(resource.id)}, operationId: ${quote(resource.operationId)},${sectionId} coreDataProducts: ${coreDataProducts} as const,${dependent}${batch}${scheduled} subjectKind: ${quote(resource.subjectKind)}, materializationIntervalSeconds: ${resource.materializationIntervalSeconds}, eligibility: { kind: ${quote(resource.eligibility.kind)} }, persistence: ${JSON.stringify(resource.persistence)} as const, implementation: ${binding} satisfies ${contract} } as const)`
  })
  const rendered = descriptors.length ? `[${descriptors.join(', ')}]` : '[]'
  const importedTypes = resources.length
    ? 'PlatformInstalledResourceDescriptor, PlatformResourceImplementationForContract'
    : 'PlatformInstalledResourceDescriptor'
  const hostTypes = resources.length
    ? "import type { PlatformEsiOperationProtocol } from '../../esi-gateway/catalog-interface.js'\nimport type { InstalledModuleResourceMaterializationPersistence, InstalledModuleResourceProjectionPersistence } from './installed-module-persistence.js'\n"
    : ''
  return `${generatedHeader}import type { ${importedTypes} } from '@eve-space/platform-module-contract/resources'\n${hostTypes}${imports}export const installedModuleResources =\n  ${rendered} as const satisfies readonly PlatformInstalledResourceDescriptor[]\n`
}

function renderResourceDeclarations(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const descriptors = manifests.flatMap((manifest) =>
    manifest.server.resources.map((resource) => {
      const sectionId = resource.sectionId ? ` sectionId: ${quote(resource.sectionId)},` : ''
      return `{ moduleId: ${quote(manifest.id)}, resourceId: ${quote(resource.id)}, operationId: ${quote(resource.operationId)},${sectionId} subjectKind: ${quote(resource.subjectKind)}, eligibility: { kind: ${quote(resource.eligibility.kind)} } }`
    }),
  )
  const rendered = descriptors.length ? `[${descriptors.join(', ')}]` : '[]'
  return `${generatedHeader}import type { PlatformInstalledResourceDeclaration } from '@eve-space/platform-module-contract/resources'\n\nexport const installedModuleResourceDeclarations =\n  ${rendered} as const satisfies readonly PlatformInstalledResourceDeclaration[]\n`
}

function renderMigrations(
  compiled: CompiledPlatformModules,
  releases: readonly ResolvedInstalledModuleRelease[],
) {
  const manifests = readCompiledPlatformModules(compiled)
  const moduleIds = manifests.map(({ id }) => id)
  const migrations: PlatformInstalledModuleMigrationDescriptor[] = manifests.flatMap((manifest) => {
    const release = releases.find(({ moduleId }) => moduleId === manifest.id)
    return manifest.server.migrations.map((migration) => ({
      moduleId: manifest.id,
      name: migration.name,
      packageName: manifest.server.package,
      exportPath:
        release?.migrations.find(({ name }) => name === migration.name)?.exportPath ??
        `./migrations/${migration.name}`,
    }))
  })
  const renderedModuleIds = moduleIds.length
    ? `[${moduleIds.map(quote).join(', ')}] as const`
    : '[] as const'
  const renderedMigrations = migrations.length
    ? `[${migrations
        .map(
          (migration) =>
            `\n  { moduleId: ${quote(migration.moduleId)}, name: ${quote(migration.name)}, packageName: ${quote(migration.packageName)}, exportPath: ${quote(migration.exportPath)} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const migrationAssignment = migrations.length
    ? `${renderedMigrations} satisfies readonly PlatformInstalledModuleMigrationDescriptor[]`
    : `\n  ${renderedMigrations} satisfies readonly PlatformInstalledModuleMigrationDescriptor[]`
  return `${generatedHeader}import type { PlatformInstalledModuleMigrationDescriptor } from '@eve-space/platform-module-contract/installed'\n\nexport const installedModuleIds = ${renderedModuleIds}\nexport const installedModuleMigrations =${migrationAssignment}\n`
}

function renderEsiOperations(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const operations = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.esiOperations.map((operation, operationIndex) => ({
      manifest,
      operation,
      binding: `module${moduleIndex}EsiOperation${operationIndex}`,
    })),
  )
  const imports = renderServerImports(
    operations.map(({ manifest, operation, binding }) => ({
      packageName: manifest.server.package,
      exportName: operation.exportName,
      localName: binding,
    })),
  )
  const catalog = operations.length
    ? `{${operations
        .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding},`)
        .join('')}\n}`
    : '{}'
  const definitions = operations.length
    ? `{${operations
        .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding},`)
        .join('')}\n}`
    : '{}'
  return `${generatedHeader}import type { PlatformEsiOperationContract } from '@eve-space/platform-module-contract/esi'\nimport type { PlatformExecutableEsiOperationDefinition } from '@eve-space/platform-module-server'\n${imports}\nexport const installedModuleEsiOperationDefinitions = ${definitions} as const satisfies Record<\n  string,\n  PlatformExecutableEsiOperationDefinition\n>\n\nexport const installedModuleEsiOperationCatalog = ${catalog.replaceAll(/(module\d+EsiOperation\d+)/g, '$1.contract')} as const satisfies Record<\n  string,\n  PlatformEsiOperationContract\n>\n\nexport const installedModuleEsiSdkOperationIds = {${operations
    .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding}.sdkOperationId,`)
    .join('')}${operations.length ? '\n' : ''}} as const satisfies Record<string, string>\n`
}

function renderPersistenceOperations(
  compiled: CompiledPlatformModules,
  routines: readonly ReviewedPersistenceRoutine[],
) {
  const manifests = readCompiledPlatformModules(compiled)
  const operations = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.persistenceOperations.map((operation, operationIndex) => ({
      manifest,
      operation,
      binding: `module${moduleIndex}PersistenceOperation${operationIndex}`,
      routine: routines.find(
        ({ identity }) =>
          identity.moduleId === manifest.id && identity.operationId === operation.id,
      ),
    })),
  )
  for (const { manifest, operation, routine } of operations)
    if (!routine)
      throw new Error(
        `Missing reviewed persistence routine ${manifest.id}/${operation.id} during registry generation`,
      )
  if (routines.length !== operations.length)
    throw new Error('Reviewed persistence routine inventory differs from module declarations')

  const imports = renderServerImports(
    operations.map(({ manifest, operation, binding }) => ({
      packageName: manifest.server.package,
      exportName: operation.exportName,
      localName: binding,
    })),
  )
  const descriptors = operations.map(({ manifest, operation, binding, routine }) => {
    const grants = persistenceOperationGrants(manifest, operation.id)
    return `{ moduleId: ${quote(manifest.id)}, operationId: ${quote(operation.id)}, method: ${quote(operation.method)}, revision: ${operation.revision}, mode: ${quote(operation.mode)}, migration: ${quote(operation.migration)}, schemaName: ${quote(routine!.identity.schemaName)}, routineName: ${quote(routine!.identity.routineName)}, definitionFingerprint: ${quote(routine!.definitionFingerprint)}, definition: ${binding} satisfies PlatformPersistenceOperationDefinition<${quote(operation.id)}, ${quote(operation.method)}, ${operation.revision}, ${quote(operation.mode)}>, grants: ${JSON.stringify(grants)} }`
  })
  const contractFingerprint = createModulePersistenceContractFingerprint(
    operations.map(({ manifest, operation, routine }) => ({
      moduleId: manifest.id,
      operationId: operation.id,
      method: operation.method,
      revision: operation.revision,
      mode: operation.mode,
      migration: operation.migration,
      schemaName: routine!.identity.schemaName,
      routineName: routine!.identity.routineName,
      definitionFingerprint: routine!.definitionFingerprint,
      grants: persistenceOperationGrants(manifest, operation.id),
    })),
    manifests.map(({ id }) => id),
  )
  const list = operations.length ? `[\n  ${descriptors.join(',\n  ')},\n]` : '[]'
  const catalog = operations.length
    ? `{${operations
        .map(({ manifest, operation }, index) => {
          const identity = `${manifest.id}/${operation.id}`
          return `\n  ${quote(identity)}: installedModulePersistenceOperations[${index}]!,`
        })
        .join('')}\n}`
    : '{}'
  const factories = renderPersistenceCapabilityFactories(manifests, operations)
  const platformImports = operations.length
    ? `import {\n  bindPlatformPersistenceOperation,\n  type PlatformInstalledPersistenceOperationDescriptor,\n  type PlatformPersistenceOperationDefinition,\n  type PlatformPersistenceOperationInvoker,\n} from '@eve-space/platform-module-server'\n`
    : "import type { PlatformInstalledPersistenceOperationDescriptor, PlatformPersistenceOperationInvoker } from '@eve-space/platform-module-server'\n"
  return `${generatedHeader}${platformImports}${imports}\nexport const installedModulePersistenceOperations = ${list} as const satisfies readonly PlatformInstalledPersistenceOperationDescriptor[]\n\nexport const installedModulePersistenceContractFingerprint = ${quote(contractFingerprint)}\n\nexport const installedModulePersistenceOperationCatalog = ${catalog} as const\n${factories}`
}

function renderPersistenceCapabilityFactories(
  manifests: readonly PlatformModuleManifest[],
  operations: readonly {
    readonly manifest: PlatformModuleManifest
    readonly operation: PlatformModuleManifest['server']['persistenceOperations'][number]
  }[],
) {
  const operationIndex = new Map(
    operations.map(({ manifest, operation }, index) => [`${manifest.id}/${operation.id}`, index]),
  )
  const factories = manifests.flatMap((manifest, moduleIndex) => [
    ...manifest.server.routes.map((route, routeIndex) => ({
      name: `createModule${moduleIndex}Route${routeIndex}Persistence`,
      group: 'routes' as const,
      key: `${manifest.id}/${route.id}`,
      manifest,
      references: route.persistenceOperations,
    })),
    ...manifest.server.activityProviders.map((provider, providerIndex) => ({
      name: `createModule${moduleIndex}ActivityProvider${providerIndex}Persistence`,
      group: 'activityProviders' as const,
      key: `${manifest.id}/${provider.id}`,
      manifest,
      references: provider.persistenceOperations,
    })),
    ...manifest.server.resources.flatMap((resource, resourceIndex) => [
      {
        name: `createModule${moduleIndex}Resource${resourceIndex}ProjectionPersistence`,
        group: 'resourceProjections' as const,
        key: `${manifest.id}/${resource.id}`,
        manifest,
        references: resource.persistence.projection,
      },
      {
        name: `createModule${moduleIndex}Resource${resourceIndex}MaterializationPersistence`,
        group: 'resourceMaterializations' as const,
        key: `${manifest.id}/${resource.id}`,
        manifest,
        references: resource.persistence.materialization,
      },
    ]),
  ])
  const declarations = factories
    .map(({ name, manifest, references }) => {
      const methods = references.map(({ operationId }) => {
        const index = operationIndex.get(`${manifest.id}/${operationId}`)
        if (index === undefined)
          throw new Error(`Missing persistence binding ${manifest.id}/${operationId}`)
        const operation = manifest.server.persistenceOperations.find(
          ({ id }) => id === operationId,
        )!
        return `${quote(operation.method)}: bindPlatformPersistenceOperation(installedModulePersistenceOperations[${index}]!, invoke),`
      })
      const parameter = methods.length > 0 ? 'invoke' : '_invoke'
      const renderedMethods = methods.length ? `\n    ${methods.join('\n    ')}\n  ` : ''
      return `\nexport function ${name}(${parameter}: PlatformPersistenceOperationInvoker) {\n  return {${renderedMethods}}\n}\n`
    })
    .join('')
  const groups = [
    'routes',
    'activityProviders',
    'resourceProjections',
    'resourceMaterializations',
  ] as const
  const catalogs = groups
    .map((group) => {
      const entries = factories
        .filter((factory) => factory.group === group)
        .map(({ key, name }) => `\n    ${quote(key)}: ${name},`)
        .join('')
      return `\n  ${group}: {${entries}${entries ? '\n  ' : ''}},`
    })
    .join('')
  return `${declarations}\nexport const installedModulePersistenceCapabilityFactories = {${catalogs}\n} as const\n\nexport type InstalledModuleResourceProjectionPersistence<\n  Key extends keyof typeof installedModulePersistenceCapabilityFactories.resourceProjections,\n> = ReturnType<(typeof installedModulePersistenceCapabilityFactories.resourceProjections)[Key]>\n\nexport type InstalledModuleResourceMaterializationPersistence<\n  Key extends keyof typeof installedModulePersistenceCapabilityFactories.resourceMaterializations,\n> = ReturnType<(typeof installedModulePersistenceCapabilityFactories.resourceMaterializations)[Key]>\n`
}

function persistenceOperationGrants(manifest: PlatformModuleManifest, operationId: string) {
  const referencesOperation = (references: readonly { readonly operationId: string }[]) =>
    references.some((reference) => reference.operationId === operationId)
  return {
    routes: manifest.server.routes
      .filter((route) => referencesOperation(route.persistenceOperations))
      .map(({ id }) => id),
    activityProviders: manifest.server.activityProviders
      .filter((provider) => referencesOperation(provider.persistenceOperations))
      .map(({ id }) => id),
    resourceProjections: manifest.server.resources
      .filter((resource) => referencesOperation(resource.persistence.projection))
      .map(({ id }) => id),
    resourceMaterializations: manifest.server.resources
      .filter((resource) => referencesOperation(resource.persistence.materialization))
      .map(({ id }) => id),
  }
}

function renderModuleRuntime(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const definitions: PlatformInstalledModuleDefinition[] = manifests.map(
    ({ id, defaultEnabled }) => ({
      moduleId: id,
      defaultEnabled,
    }),
  )
  const sections: PlatformInstalledModuleSectionDefinition[] = manifests.flatMap((manifest) =>
    (manifest.sections ?? []).map((section) =>
      section.kind === 'sensitive-evidence'
        ? {
            moduleId: manifest.id,
            id: section.id,
            kind: section.kind,
            defaultEnabled: section.defaultEnabled,
            disclosureRevision: section.disclosureRevision,
          }
        : {
            moduleId: manifest.id,
            id: section.id,
            kind: section.kind,
            defaultEnabled: section.defaultEnabled,
          },
    ),
  )
  const admissionScopes = installedOrganizationAdmissionScopes(manifests)
  const navigation: PlatformNavigationDefault[] = [
    ...coreNavigationDefaults,
    ...manifests.flatMap((manifest) =>
      manifest.nuxt.navigation.map(({ id, placement, order, sectionId }) => ({
        ownerId: manifest.id,
        navigationId: id,
        placement,
        order,
        sectionId,
      })),
    ),
  ].toSorted(compareRuntimeNavigation)
  const renderedDefinitions = definitions.length
    ? `[${definitions
        .map(
          ({ moduleId, defaultEnabled }) =>
            `\n  { moduleId: ${quote(moduleId)}, defaultEnabled: ${defaultEnabled} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const renderedNavigation = navigation.length
    ? `[${navigation
        .map(({ ownerId, navigationId, placement, order, sectionId }) => {
          const renderedSectionId = sectionId ? `, sectionId: ${quote(sectionId)}` : ''
          return `\n  { ownerId: ${quote(ownerId)}, navigationId: ${quote(navigationId)}, placement: ${quote(placement)}, order: ${order}${renderedSectionId} },`
        })
        .join('')}\n] as const`
    : '[] as const'
  const definitionAssignment = definitions.length
    ? ` ${renderedDefinitions} satisfies readonly PlatformInstalledModuleDefinition[]`
    : `\n  ${renderedDefinitions} satisfies readonly PlatformInstalledModuleDefinition[]`
  const renderedAdmissionScopes = admissionScopes.length
    ? `[${admissionScopes
        .map(
          ({
            publisherPackage,
            moduleId,
            admissionScope,
            audience,
            requiredPermission,
            additionalRequiredPermissions,
          }) => {
            const renderedAdditionalPermissions = additionalRequiredPermissions
              ? `, additionalRequiredPermissions: ${JSON.stringify(additionalRequiredPermissions)} as const`
              : ''
            return `\n  { publisherPackage: ${quote(publisherPackage)}, moduleId: ${quote(moduleId)}, admissionScope: ${quote(admissionScope)}, audience: ${quote(audience)}, requiredPermission: ${quote(requiredPermission)}${renderedAdditionalPermissions} },`
          },
        )
        .join('')}\n] as const`
    : '[] as const'
  const renderedSections = sections.length
    ? `[${sections
        .map((section) => {
          const disclosureRevision =
            section.kind === 'sensitive-evidence'
              ? `, disclosureRevision: ${section.disclosureRevision}`
              : ''
          return `\n  { moduleId: ${quote(section.moduleId)}, id: ${quote(section.id)}, kind: ${quote(section.kind)}, defaultEnabled: false${disclosureRevision} },`
        })
        .join('')}\n] as const`
    : '[] as const'
  return `${generatedHeader}import type {\n  PlatformInstalledModuleDefinition,\n  PlatformInstalledModuleSectionDefinition,\n  PlatformInstalledOrganizationAdmissionScopeDescriptor,\n} from '@eve-space/platform-module-contract/installed'\nimport type { PlatformNavigationDefault } from '@eve-space/platform-module-contract/nuxt'\n\nexport const installedModuleDefinitions =${definitionAssignment}\nexport const installedModuleSectionDefinitions = ${renderedSections} satisfies readonly PlatformInstalledModuleSectionDefinition[]\nexport const installedModuleOrganizationAdmissionScopes = ${renderedAdmissionScopes} satisfies readonly PlatformInstalledOrganizationAdmissionScopeDescriptor[]\nexport const platformNavigationDefaults = ${renderedNavigation} satisfies readonly PlatformNavigationDefault[]\n`
}

function installedOrganizationAdmissionScopes(
  manifests: readonly PlatformModuleManifest[],
): PlatformInstalledOrganizationAdmissionScopeDescriptor[] {
  const scopes = new Map<string, PlatformInstalledOrganizationAdmissionScopeDescriptor>()
  for (const manifest of manifests)
    for (const authorization of [...manifest.server.routes, ...manifest.server.activityProviders]) {
      const admissionScope = platformOrganizationAdmissionScope(manifest.id, authorization)
      scopes.set(admissionScope, {
        publisherPackage: manifest.release.publisherPackage,
        moduleId: manifest.id,
        admissionScope,
        audience: authorization.audience,
        requiredPermission: authorization.requiredPermission,
        additionalRequiredPermissions: authorization.additionalRequiredPermissions,
      })
    }
  return [...scopes.values()].toSorted((left, right) =>
    compareStable(left.admissionScope, right.admissionScope),
  )
}

function renderNuxtModules(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const imports = manifests.map(
    (manifest, index) => `import module${index} from ${quote(manifest.nuxt.package)}\n`,
  )
  const moduleBindings = manifests.map((_manifest, index) => `module${index}`).join(', ')
  return `${generatedHeader}${imports.join('')}export const installedNuxtModules = [${moduleBindings}] as const\n`
}

function renderNuxtContributions(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const contributions: PlatformNuxtContributionDescriptor[] = manifests.map((manifest) => ({
    moduleId: manifest.id,
    packageName: manifest.nuxt.package,
    defaultIcon: manifest.icon,
    sections: manifest.sections ?? [],
    reviewerContributions: reviewerNuxtContributionDescriptors(manifest),
    queryAdmissionScopes: manifest.server.routes.map((route) => ({
      routeId: route.id,
      authorization: route.authorization,
      audience: route.audience,
      requiredPermission: route.requiredPermission,
      additionalRequiredPermissions: route.additionalRequiredPermissions,
      sectionId: route.sectionId,
      target: route.target,
      exposure: route.exposure,
      admissionScope: platformOrganizationAdmissionScope(manifest.id, route),
    })),
    pages: manifest.nuxt.pages,
    navigation: manifest.nuxt.navigation,
    exposed: manifest.nuxt.exposed,
  }))
  const rendered = contributions.length ? JSON.stringify(contributions, undefined, 2) : '[]'
  return `${generatedHeader}import type { PlatformNuxtContributionDescriptor } from '@eve-space/platform-module-contract/nuxt'\n\nexport const installedNuxtContributions =\n  ${rendered} as const satisfies readonly PlatformNuxtContributionDescriptor[]\n`
}

function reviewerNuxtContributionDescriptors(
  manifest: PlatformModuleManifest,
): PlatformReviewerNuxtContribution[] {
  return (manifest.reviewerContributions ?? [])
    .map((contribution) => {
      const route = resolveReviewerContributionRoute(manifest, contribution)
      return {
        contributionId: contribution.id,
        routeId: route.id,
        routePath: resolvePlatformModuleRoutePath(route.namespace),
        sectionId: route.sectionId,
        audience: contribution.audience,
        requiredPermission: contribution.requiredPermission,
        target: contribution.target,
        panelExport: contribution.panelExport,
        label: contribution.label,
        description: contribution.description,
        icon: contribution.icon,
        order: contribution.order,
      }
    })
    .toSorted(
      (left, right) =>
        left.order - right.order || compareStable(left.contributionId, right.contributionId),
    )
}

function renderInstalledInventory(
  compiled: CompiledPlatformModules,
  releases: readonly ResolvedInstalledModuleRelease[],
) {
  const manifests = readCompiledPlatformModules(compiled)
  const inventory = manifests.map((manifest) => {
    const release = releases.find(({ moduleId }) => moduleId === manifest.id)
    if (!release)
      return {
        publisherPackage: manifest.release.publisherPackage,
        moduleId: manifest.id,
        releaseVersion: manifest.release.version,
        packages: {
          manifest: {
            name: manifest.release.publisherPackage,
            version: manifest.release.version,
            integrity: 'unresolved',
          },
          server: {
            name: manifest.server.package,
            version: manifest.release.version,
            integrity: 'unresolved',
          },
          nuxt: {
            name: manifest.nuxt.package,
            version: manifest.release.version,
            integrity: 'unresolved',
          },
        },
      }
    return {
      publisherPackage: release.publisherPackage,
      moduleId: release.moduleId,
      releaseVersion: release.version,
      packages: {
        manifest: packageProvenance(release.packages.manifest),
        server: packageProvenance(release.packages.server),
        nuxt: packageProvenance(release.packages.nuxt),
      },
    }
  })
  return `${generatedHeader}import type { PlatformInstalledModuleProvenance } from '@eve-space/platform-module-contract/installed'\n\nexport const installedModuleInventory =\n  ${JSON.stringify(inventory, undefined, 2)} as const satisfies readonly PlatformInstalledModuleProvenance[]\n`
}

function renderInstalledPermissionCatalog(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const permissions = manifests.flatMap((manifest) =>
    (manifest.permissions ?? []).map((permission) => ({
      publisherPackage: manifest.release.publisherPackage,
      moduleId: manifest.id,
      key: permission.key,
      label: permission.label,
      purpose: permission.purpose,
      audiences: permission.audiences,
      sensitivity: permission.sensitivity,
      reviewAllowed: permission.reviewAllowed,
    })),
  )
  const profiles = manifests.flatMap((manifest) =>
    (manifest.permissionProfiles ?? []).map((profile) => ({
      publisherPackage: manifest.release.publisherPackage,
      moduleId: manifest.id,
      id: profile.id,
      label: profile.label,
      description: profile.description,
      audiences: profile.audiences,
      permissions: profile.permissions,
    })),
  )
  return `${generatedHeader}import type {\n  PlatformInstalledPermissionDescriptor,\n  PlatformInstalledPermissionProfileDescriptor,\n} from '@eve-space/platform-module-contract/installed'\n\nexport const installedPermissionCatalog =\n  ${JSON.stringify(permissions, undefined, 2)} as const satisfies readonly PlatformInstalledPermissionDescriptor[]\nexport const installedPermissionProfileCatalog =\n  ${JSON.stringify(profiles, undefined, 2)} as const satisfies readonly PlatformInstalledPermissionProfileDescriptor[]\n`
}

function renderInstalledReviewerContributions(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const contributions = installedReviewerContributionDescriptors(manifests)
  const rendered = contributions.length ? JSON.stringify(contributions, undefined, 2) : '[]'
  return `${generatedHeader}import type { PlatformInstalledReviewerContributionDescriptor } from '@eve-space/platform-module-contract/installed'\n\nexport const installedReviewerContributions =\n  ${rendered} as const satisfies readonly PlatformInstalledReviewerContributionDescriptor[]\n`
}

function installedReviewerContributionDescriptors(
  manifests: readonly PlatformModuleManifest[],
): PlatformInstalledReviewerContributionDescriptor[] {
  return manifests
    .flatMap((manifest) =>
      (manifest.reviewerContributions ?? []).map((contribution) => {
        const route = resolveReviewerContributionRoute(manifest, contribution)
        return {
          publisherPackage: manifest.release.publisherPackage,
          moduleId: manifest.id,
          contributionId: contribution.id,
          routeId: route.id,
          routePath: resolvePlatformModuleRoutePath(route.namespace),
          sectionId: route.sectionId,
          audience: contribution.audience,
          requiredPermission: contribution.requiredPermission,
          directoryPermission: contribution.directoryPermission,
          target: contribution.target,
          panelPackage: manifest.nuxt.package,
          panelExport: contribution.panelExport,
          label: contribution.label,
          description: contribution.description,
          icon: contribution.icon,
          order: contribution.order,
        }
      }),
    )
    .toSorted(
      (left, right) =>
        left.order - right.order ||
        compareStable(left.moduleId, right.moduleId) ||
        compareStable(left.contributionId, right.contributionId),
    )
}

function resolveReviewerContributionRoute(
  manifest: PlatformModuleManifest,
  contribution: NonNullable<PlatformModuleManifest['reviewerContributions']>[number],
) {
  const routes = manifest.server.routes.filter(({ id }) => id === contribution.routeId)
  if (routes.length !== 1)
    throw new Error(
      `Validated reviewer contribution ${manifest.id}/${contribution.id} must resolve exactly one route ${contribution.routeId}`,
    )
  const route = routes[0]!
  if (
    route.audience !== contribution.audience ||
    route.requiredPermission !== contribution.requiredPermission ||
    route.target !== contribution.target ||
    (route.additionalRequiredPermissions?.length ?? 0) > 0
  )
    throw new Error(
      `Validated reviewer contribution ${manifest.id}/${contribution.id} has an incompatible route ${contribution.routeId}`,
    )
  return route
}

function packageProvenance(artifact: ResolvedModulePackage) {
  return {
    name: artifact.name,
    version: artifact.version,
    integrity: artifact.integrity,
  }
}

function renderNavigation(compiled: CompiledPlatformModules) {
  const manifests = readCompiledPlatformModules(compiled)
  const navigation: PlatformInstalledNavigation[] = manifests
    .flatMap((manifest) =>
      manifest.nuxt.navigation.map((entry) => ({
        moduleId: manifest.id,
        ...entry,
        icon: entry.icon ?? manifest.icon,
      })),
    )
    .toSorted(compareNavigation)
  if (navigation.length === 0)
    return `${generatedHeader}import type { PlatformInstalledNavigation } from '@eve-space/platform-module-contract/nuxt'\n\nexport const installedModuleNavigation =\n  [] as const satisfies readonly PlatformInstalledNavigation[]\n`
  return `${generatedHeader}import type { PlatformInstalledNavigation } from '@eve-space/platform-module-contract/nuxt'\n\nexport const installedModuleNavigation = [${navigation.map(renderNavigationEntry).join('')}\n] as const satisfies readonly PlatformInstalledNavigation[]\n`
}

function renderNavigationEntry(entry: PlatformInstalledNavigation) {
  const sectionId = entry.sectionId ? `    sectionId: ${quote(entry.sectionId)},\n` : ''
  return `\n  {\n    moduleId: ${quote(entry.moduleId)},\n${sectionId}    id: ${quote(entry.id)},\n    label: ${quote(entry.label)},\n    description: ${quote(entry.description)},\n    to: ${quote(entry.to)},\n    icon: ${quote(entry.icon)},\n    audience: ${quote(entry.audience)},\n    placement: ${quote(entry.placement)},\n    order: ${entry.order},\n    pageName: ${quote(entry.pageName)},\n  },`
}

function compareNavigation(left: PlatformInstalledNavigation, right: PlatformInstalledNavigation) {
  return (
    left.order - right.order ||
    compareStable(left.moduleId, right.moduleId) ||
    compareStable(left.id, right.id)
  )
}

function compareRuntimeNavigation(
  left: PlatformNavigationDefault,
  right: PlatformNavigationDefault,
) {
  return (
    platformNavigationPlacements.indexOf(left.placement) -
      platformNavigationPlacements.indexOf(right.placement) ||
    left.order - right.order ||
    compareStable(left.ownerId, right.ownerId) ||
    compareStable(left.navigationId, right.navigationId)
  )
}

function renderServerImports(
  imports: readonly { packageName: string; exportName: string; localName: string }[],
) {
  const specifiersByPackage = new Map<string, string[]>()
  for (const { packageName, exportName, localName } of imports) {
    const specifiers = specifiersByPackage.get(packageName) ?? []
    specifiers.push(`${exportName} as ${localName}`)
    specifiersByPackage.set(packageName, specifiers)
  }
  return [...specifiersByPackage]
    .map(([packageName, specifiers]) => {
      if (specifiers.length === 1) return `import { ${specifiers[0]} } from ${quote(packageName)}\n`
      const renderedSpecifiers = specifiers.map((specifier) => `  ${specifier},`).join('\n')
      return `import {\n${renderedSpecifiers}\n} from ${quote(packageName)}\n`
    })
    .join('')
}

function quote(value: string) {
  const backslash = String.fromCodePoint(92)
  const escapedSingleQuote = String.raw`\'`
  const escapedNewline = String.raw`\n`
  const escaped = value
    .replaceAll(backslash, backslash.repeat(2))
    .replaceAll("'", escapedSingleQuote)
    .replaceAll('\n', escapedNewline)
  return "'" + escaped + "'"
}

function compareStable(left: string, right: string) {
  if (left < right) return -1
  if (left > right) return 1
  return 0
}

export function assertOutputPath(root: string, path: string) {
  const output = resolve(root, path)
  const relativeOutput = relative(root, output)
  if (
    relativeOutput.startsWith(`..${sep}`) ||
    relativeOutput === '..' ||
    dirname(output) === output
  )
    throw new Error(`Generated output escapes the repository: ${path}`)
  return output
}
