import { existsSync, readFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { pathToFileURL } from 'node:url'
import {
  compareStable,
  platformNavigationPlacements,
  validatePlatformModuleManifests,
  type PlatformInstalledModuleMigrationDescriptor,
  type PlatformInstalledModuleDefinition,
  type PlatformInstalledNavigation,
  type PlatformModuleManifest,
  type PlatformNavigationDefault,
  type PlatformNuxtContributionDescriptor,
} from '../../packages/platform-module-contract/src/index.js'
import { coreModuleValidationAuthorities, coreNavigationDefaults } from './authorities.js'

export const generatedRegistryPaths = [
  'api/src/generated/platform/installed-module-routes.ts',
  'api/src/generated/platform/installed-module-worker.ts',
  'api/src/generated/platform/installed-module-migrations.ts',
  'api/src/generated/platform/installed-module-esi.ts',
  'api/src/generated/platform/installed-module-runtime.ts',
  'generated/platform/installed-nuxt-modules.ts',
  'generated/platform/installed-nuxt-contributions.ts',
  'generated/platform/installed-module-navigation.ts',
] as const

const generatedHeader =
  '// This file is generated by scripts/generate-module-registries.ts. Do not edit.\n\n'

export async function loadInstalledModuleManifests(root: string) {
  const installedPath = join(root, 'features/installed-modules.json')
  const installed: unknown = JSON.parse(readFileSync(installedPath, 'utf8'))
  if (!isRecord(installed))
    throw new Error('features/installed-modules.json must contain a string modules array')
  if (!Array.isArray(installed.modules) || !installed.modules.every((id) => typeof id === 'string'))
    throw new Error('features/installed-modules.json must contain a string modules array')

  const ids = installed.modules
  const manifests = await Promise.all(
    ids.map(async (id) => {
      const featureDirectory = join(root, 'features', id)
      const descriptorPath = join(featureDirectory, 'module.config.ts')
      if (!existsSync(descriptorPath))
        throw new Error(`Installed module ${id} is missing ${relative(root, descriptorPath)}`)

      const imported: unknown = await import(`${pathToFileURL(descriptorPath).href}?registry`)
      if (!isRecord(imported))
        throw new Error(`Installed module ${id} must default-export its manifest`)
      const manifest = parsePlatformModuleManifest(imported.default, id)
      if (manifest.id !== id)
        throw new Error(`Installed module ${id} descriptor declares mismatched ID ${manifest.id}`)

      validatePackageManifest(
        featureDirectory,
        'server',
        manifest.server.package,
        manifest.server.migrations.map(({ name }) => name),
      )
      validatePackageManifest(featureDirectory, 'nuxt', manifest.nuxt.package)
      return manifest
    }),
  )

  const validated = validatePlatformModuleManifests(manifests, coreModuleValidationAuthorities)
  validateDeploymentDependencies(root, validated)
  return validated
}

export function generateRegistryFiles(manifests: readonly PlatformModuleManifest[]) {
  const sorted = validatePlatformModuleManifests(manifests, coreModuleValidationAuthorities)
  return new Map<string, string>([
    [generatedRegistryPaths[0], renderApiRoutes(sorted)],
    [generatedRegistryPaths[1], renderWorkerResources(sorted)],
    [generatedRegistryPaths[2], renderMigrations(sorted)],
    [generatedRegistryPaths[3], renderEsiOperations(sorted)],
    [generatedRegistryPaths[4], renderModuleRuntime(sorted)],
    [generatedRegistryPaths[5], renderNuxtModules(sorted)],
    [generatedRegistryPaths[6], renderNuxtContributions(sorted)],
    [generatedRegistryPaths[7], renderNavigation(sorted)],
  ])
}

function validatePackageManifest(
  featureDirectory: string,
  kind: 'server' | 'nuxt',
  expected: string,
  migrations: readonly string[] = [],
) {
  const packagePath = join(featureDirectory, kind, 'package.json')
  if (!existsSync(packagePath)) throw new Error(`Module package is missing ${packagePath}`)
  const packageJson: unknown = JSON.parse(readFileSync(packagePath, 'utf8'))
  if (!isRecord(packageJson)) throw new Error(`${packagePath} must contain a JSON object`)
  if (packageJson.name !== expected)
    throw new Error(`${packagePath} must declare package name ${expected}`)
  if (!Array.isArray(packageJson.files) || !packageJson.files.includes('dist'))
    throw new Error(`${packagePath} files must include dist`)
  if (!isRecord(packageJson.exports) || !('.' in packageJson.exports))
    throw new Error(`${packagePath} must export its runtime`)
  if (kind !== 'server') return

  if (!packageJson.files.includes('migrations'))
    throw new Error(`${packagePath} files must include migrations`)
  if (!('./migrations/*' in packageJson.exports))
    throw new Error(`${packagePath} must export ./migrations/*`)
  for (const migration of migrations) {
    const migrationPath = join(featureDirectory, 'server', 'migrations', migration)
    if (!existsSync(migrationPath)) throw new Error(`Module migration is missing ${migrationPath}`)
  }
}

function validateDeploymentDependencies(
  root: string,
  manifests: readonly PlatformModuleManifest[],
) {
  const rootPackage = readPackageJson(join(root, 'package.json'))
  const apiPackage = readPackageJson(join(root, 'api/package.json'))
  const expectedServer = new Set(manifests.map((manifest) => manifest.server.package))
  const expectedNuxt = new Set(manifests.map((manifest) => manifest.nuxt.package))
  const rootDependencies = dependencyNames(rootPackage)
  const apiDependencies = dependencyNames(apiPackage)
  const actualServer = new Set(
    [...apiDependencies].filter(
      (name) =>
        name !== '@eve-space/platform-module-server' && /^@eve-space\/.+-server$/.test(name),
    ),
  )
  const actualNuxt = new Set(
    [...rootDependencies].filter(
      (name) => name !== '@eve-space/platform-module-nuxt' && /^@eve-space\/.+-nuxt$/.test(name),
    ),
  )

  assertExactDependencies('API feature server', actualServer, expectedServer)
  assertExactDependencies('root feature Nuxt', actualNuxt, expectedNuxt)
  for (const packageName of expectedNuxt)
    if (apiDependencies.has(packageName))
      throw new Error(`API dependencies must not include feature Nuxt package ${packageName}`)
  for (const packageName of expectedServer)
    if (rootDependencies.has(packageName))
      throw new Error(`Root dependencies must not include feature server package ${packageName}`)
}

function readPackageJson(path: string) {
  const value: unknown = JSON.parse(readFileSync(path, 'utf8'))
  if (!isRecord(value)) throw new Error(`${path} must contain a JSON object`)
  return value
}

function dependencyNames(packageJson: Record<string, unknown>) {
  return new Set(isRecord(packageJson.dependencies) ? Object.keys(packageJson.dependencies) : [])
}

function assertExactDependencies(label: string, actual: Set<string>, expected: Set<string>) {
  const missing = [...expected].filter((name) => !actual.has(name))
  const extra = [...actual].filter((name) => !expected.has(name))
  if (missing.length || extra.length)
    throw new Error(
      `${label} dependencies differ from installed modules (missing: ${missing.join(', ') || 'none'}; extra: ${extra.join(', ') || 'none'})`,
    )
}

function renderApiRoutes(manifests: readonly PlatformModuleManifest[]) {
  const routes = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.routes.map((route, routeIndex) => ({
      manifest,
      route,
      binding: `module${moduleIndex}Route${routeIndex}`,
    })),
  )
  const imports = routes.map(
    ({ manifest, route, binding }) =>
      `import { ${route.exportName} as ${binding}Factory } from ${quote(manifest.server.package)}\n`,
  )
  const platformImports = routes.length
    ? [
        "import { platformModuleRouteComposers } from '../../platform/module-route-composition.js'",
        "import { createPlatformModuleRouteCapabilities } from '../../platform/module-route-capabilities.js'",
      ]
        .filter(Boolean)
        .join('\n') + '\n'
    : ''
  const factories = routes.map(
    ({ manifest, binding }) =>
      `const ${binding} = ${binding}Factory(createPlatformModuleRouteCapabilities(${quote(manifest.id)}))\n`,
  )
  const chain = routes.map(
    ({ manifest, route, binding }) =>
      `\n  .route(\n    ${quote(route.namespace)},\n    platformModuleRouteComposers[${quote(route.authorization)}](${quote(manifest.id)}, ${binding}),\n  )`,
  )
  const composition = routes.length
    ? `${platformImports}${imports.join('')}\n${factories.join('')}\n`
    : '\n'
  return `${generatedHeader}import { Hono } from 'hono'\n${composition}export const installedModuleRoutes = new Hono()${chain.join('')}\n`
}

function renderWorkerResources(manifests: readonly PlatformModuleManifest[]) {
  const resources = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.resources.map((resource, resourceIndex) => ({
      manifest,
      resource,
      binding: `module${moduleIndex}Resource${resourceIndex}`,
    })),
  )
  const imports = resources.map(
    ({ manifest, resource, binding }) =>
      `import { ${resource.exportName} as ${binding} } from ${quote(manifest.server.package)}\n`,
  )
  const descriptors = resources.map(({ manifest, resource, binding }) => {
    const batch = resource.batch
      ? ` batch: { mode: ${quote(resource.batch.mode)}, operationId: ${quote(resource.batch.operationId)} },`
      : ''
    return `{ moduleId: ${quote(manifest.id)}, resourceId: ${quote(resource.id)}, operationId: ${quote(resource.operationId)},${batch} subjectKind: ${quote(resource.subjectKind)}, materializationIntervalSeconds: ${resource.materializationIntervalSeconds}, eligibility: { kind: ${quote(resource.eligibility.kind)} }, implementation: ${binding} }`
  })
  const rendered = descriptors.length ? `[${descriptors.join(', ')}]` : '[]'
  return `${generatedHeader}import type {\n  PlatformInstalledResourceDescriptor,\n  PlatformResourceOperationImplementation,\n} from '@eve-space/platform-module-contract'\n${imports.join('')}export const installedModuleResources =\n  ${rendered} as const satisfies readonly PlatformInstalledResourceDescriptor<PlatformResourceOperationImplementation>[]\n`
}

function renderMigrations(manifests: readonly PlatformModuleManifest[]) {
  const moduleIds = manifests.map(({ id }) => id)
  const migrations: PlatformInstalledModuleMigrationDescriptor[] = manifests.flatMap((manifest) =>
    manifest.server.migrations.map((migration) => ({ moduleId: manifest.id, ...migration })),
  )
  const renderedModuleIds = moduleIds.length
    ? `[${moduleIds.map(quote).join(', ')}] as const`
    : '[] as const'
  const renderedMigrations = migrations.length
    ? `[${migrations
        .map(
          (migration) =>
            `\n  { moduleId: ${quote(migration.moduleId)}, name: ${quote(migration.name)} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const migrationAssignment = migrations.length
    ? `${renderedMigrations} satisfies readonly PlatformInstalledModuleMigrationDescriptor[]`
    : `\n  ${renderedMigrations} satisfies readonly PlatformInstalledModuleMigrationDescriptor[]`
  return `${generatedHeader}import type { PlatformInstalledModuleMigrationDescriptor } from '@eve-space/platform-module-contract'\n\nexport const installedModuleIds = ${renderedModuleIds}\nexport const installedModuleMigrations =${migrationAssignment}\n`
}

function renderEsiOperations(manifests: readonly PlatformModuleManifest[]) {
  const operations = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.esiOperations.map((operation, operationIndex) => ({
      manifest,
      operation,
      binding: `module${moduleIndex}EsiOperation${operationIndex}`,
    })),
  )
  const imports = operations.map(
    ({ manifest, operation, binding }) =>
      `import { ${operation.exportName} as ${binding} } from ${quote(manifest.server.package)}\n`,
  )
  const catalog = operations.length
    ? `{${operations
        .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding},`)
        .join('')}\n}`
    : '{}'
  const definitions = operations.length
    ? `{${operations
        .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding},`)
        .join('')}\n}`
    : '{}'
  return `${generatedHeader}import type { PlatformEsiOperationContract } from '@eve-space/platform-module-contract'\nimport type { PlatformExecutableEsiOperationDefinition } from '@eve-space/platform-module-server'\n${imports.join('')}\nexport const installedModuleEsiOperationDefinitions = ${definitions} as const satisfies Record<\n  string,\n  PlatformExecutableEsiOperationDefinition\n>\n\nexport const installedModuleEsiOperationCatalog = ${catalog.replaceAll(/(module\d+EsiOperation\d+)/g, '$1.contract')} as const satisfies Record<\n  string,\n  PlatformEsiOperationContract\n>\n\nexport const installedModuleEsiSdkOperationIds = {${operations
    .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding}.sdkOperationId,`)
    .join('')}${operations.length ? '\n' : ''}} as const satisfies Record<string, string>\n`
}

function renderModuleRuntime(manifests: readonly PlatformModuleManifest[]) {
  const definitions: PlatformInstalledModuleDefinition[] = manifests.map(
    ({ id, defaultEnabled }) => ({
      moduleId: id,
      defaultEnabled,
    }),
  )
  const navigation: PlatformNavigationDefault[] = [
    ...coreNavigationDefaults,
    ...manifests.flatMap((manifest) =>
      manifest.nuxt.navigation.map(({ id, placement, order }) => ({
        ownerId: manifest.id,
        navigationId: id,
        placement,
        order,
      })),
    ),
  ].toSorted(compareRuntimeNavigation)
  const renderedDefinitions = definitions.length
    ? `[${definitions
        .map(
          ({ moduleId, defaultEnabled }) =>
            `\n  { moduleId: ${quote(moduleId)}, defaultEnabled: ${defaultEnabled} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const renderedNavigation = navigation.length
    ? `[${navigation
        .map(
          ({ ownerId, navigationId, placement, order }) =>
            `\n  { ownerId: ${quote(ownerId)}, navigationId: ${quote(navigationId)}, placement: ${quote(placement)}, order: ${order} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const definitionAssignment = definitions.length
    ? ` ${renderedDefinitions} satisfies readonly PlatformInstalledModuleDefinition[]`
    : `\n  ${renderedDefinitions} satisfies readonly PlatformInstalledModuleDefinition[]`
  return `${generatedHeader}import type {\n  PlatformInstalledModuleDefinition,\n  PlatformNavigationDefault,\n} from '@eve-space/platform-module-contract'\n\nexport const installedModuleDefinitions =${definitionAssignment}\nexport const platformNavigationDefaults = ${renderedNavigation} satisfies readonly PlatformNavigationDefault[]\n`
}

function renderNuxtModules(manifests: readonly PlatformModuleManifest[]) {
  const imports = manifests.map(
    (manifest, index) => `import module${index} from ${quote(manifest.nuxt.package)}\n`,
  )
  const moduleBindings = manifests.map((_manifest, index) => `module${index}`).join(', ')
  return `${generatedHeader}${imports.join('')}export const installedNuxtModules = [${moduleBindings}] as const\n`
}

function renderNuxtContributions(manifests: readonly PlatformModuleManifest[]) {
  const contributions: PlatformNuxtContributionDescriptor[] = manifests.map((manifest) => ({
    moduleId: manifest.id,
    defaultIcon: manifest.icon,
    pages: manifest.nuxt.pages,
    navigation: manifest.nuxt.navigation,
    ...(manifest.nuxt.exposed ? { exposed: manifest.nuxt.exposed } : {}),
  }))
  const rendered = contributions.length ? JSON.stringify(contributions, undefined, 2) : '[]'
  return `${generatedHeader}import type { PlatformNuxtContributionDescriptor } from '@eve-space/platform-module-contract'\n\nexport const installedNuxtContributions =\n  ${rendered} as const satisfies readonly PlatformNuxtContributionDescriptor[]\n`
}

function renderNavigation(manifests: readonly PlatformModuleManifest[]) {
  const navigation: PlatformInstalledNavigation[] = manifests
    .flatMap((manifest) =>
      manifest.nuxt.navigation.map((entry) => ({
        moduleId: manifest.id,
        ...entry,
        icon: entry.icon ?? manifest.icon,
      })),
    )
    .toSorted(compareNavigation)
  if (navigation.length === 0)
    return `${generatedHeader}import type { PlatformInstalledNavigation } from '@eve-space/platform-module-contract'\n\nexport const installedModuleNavigation =\n  [] as const satisfies readonly PlatformInstalledNavigation[]\n`
  return `${generatedHeader}import type { PlatformInstalledNavigation } from '@eve-space/platform-module-contract'\n\nexport const installedModuleNavigation = [${navigation.map(renderNavigationEntry).join('')}\n] as const satisfies readonly PlatformInstalledNavigation[]\n`
}

function renderNavigationEntry(entry: PlatformInstalledNavigation) {
  return `\n  {\n    moduleId: ${quote(entry.moduleId)},\n    id: ${quote(entry.id)},\n    label: ${quote(entry.label)},\n    description: ${quote(entry.description)},\n    to: ${quote(entry.to)},\n    icon: ${quote(entry.icon)},\n    audience: ${quote(entry.audience)},\n    placement: ${quote(entry.placement)},\n    order: ${entry.order},\n    pageName: ${quote(entry.pageName)},\n  },`
}

function compareNavigation(left: PlatformInstalledNavigation, right: PlatformInstalledNavigation) {
  return (
    left.order - right.order ||
    compareStable(left.moduleId, right.moduleId) ||
    compareStable(left.id, right.id)
  )
}

function compareRuntimeNavigation(
  left: PlatformNavigationDefault,
  right: PlatformNavigationDefault,
) {
  return (
    platformNavigationPlacements.indexOf(left.placement) -
      platformNavigationPlacements.indexOf(right.placement) ||
    left.order - right.order ||
    compareStable(left.ownerId, right.ownerId) ||
    compareStable(left.navigationId, right.navigationId)
  )
}

function quote(value: string) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n')}'`
}

function parsePlatformModuleManifest(value: unknown, moduleId: string): PlatformModuleManifest {
  if (
    !isRecord(value) ||
    typeof value.id !== 'string' ||
    typeof value.icon !== 'string' ||
    typeof value.defaultEnabled !== 'boolean' ||
    !isRecord(value.server) ||
    typeof value.server.package !== 'string' ||
    !Array.isArray(value.server.routes) ||
    !Array.isArray(value.server.migrations) ||
    !Array.isArray(value.server.resources) ||
    !Array.isArray(value.server.esiOperations) ||
    !isRecord(value.nuxt) ||
    typeof value.nuxt.package !== 'string' ||
    !Array.isArray(value.nuxt.pages) ||
    !Array.isArray(value.nuxt.navigation) ||
    (value.nuxt.exposed !== undefined && !isRecord(value.nuxt.exposed))
  )
    throw new Error(`Installed module ${moduleId} must default-export its manifest`)
  return value as unknown as PlatformModuleManifest
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

export function assertOutputPath(root: string, path: string) {
  const output = resolve(root, path)
  const relativeOutput = relative(root, output)
  if (
    relativeOutput.startsWith(`..${sep}`) ||
    relativeOutput === '..' ||
    dirname(output) === output
  )
    throw new Error(`Generated output escapes the repository: ${path}`)
  return output
}
