import { existsSync, readFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { pathToFileURL } from 'node:url'
import {
  compareStable,
  platformNavigationPlacements,
  validatePlatformModuleManifests,
  type PlatformInstalledModuleMigrationDescriptor,
  type PlatformInstalledActivityProviderDescriptor,
  type PlatformInstalledModuleDefinition,
  type PlatformInstalledNavigation,
  type PlatformModuleManifest,
  type PlatformNavigationDefault,
  type PlatformNuxtContributionDescriptor,
} from '../../packages/platform-module-contract/src/index.js'
import {
  canonicalizePersistenceRoutineSql,
  type CanonicalPersistenceRoutine,
} from '../../api/src/db/module-persistence-routine.js'
import { createModulePersistenceContractFingerprint } from '../../api/src/db/module-persistence-contract.js'
import { coreModuleValidationAuthorities, coreNavigationDefaults } from './authorities.js'
import {
  assertInstalledFeatureBoundaries,
  assertManifestCompositionBoundaries,
} from './feature-boundaries.js'

export const generatedRegistryPaths = [
  'api/src/generated/platform/installed-module-routes.ts',
  'api/src/generated/platform/installed-module-activity-providers.ts',
  'api/src/generated/platform/installed-module-worker.ts',
  'api/src/generated/platform/installed-module-migrations.ts',
  'api/src/generated/platform/installed-module-esi.ts',
  'api/src/generated/platform/installed-module-persistence.ts',
  'api/src/generated/platform/installed-module-runtime.ts',
  'generated/platform/installed-nuxt-modules.ts',
  'generated/platform/installed-nuxt-contributions.ts',
  'generated/platform/installed-module-navigation.ts',
] as const

interface ReviewedPersistenceRoutine extends CanonicalPersistenceRoutine {
  readonly migration: string
}

export interface InstalledModuleRegistryInput {
  readonly manifests: readonly PlatformModuleManifest[]
  readonly persistenceRoutines: readonly ReviewedPersistenceRoutine[]
}

const generatedHeader =
  '// This file is generated by scripts/generate-module-registries.ts. Do not edit.\n\n'

export async function loadInstalledModuleManifests(root: string) {
  const installedPath = join(root, 'features/installed-modules.json')
  const installed: unknown = JSON.parse(readFileSync(installedPath, 'utf8'))
  if (!isRecord(installed))
    throw new Error('features/installed-modules.json must contain a string modules array')
  if (!Array.isArray(installed.modules) || !installed.modules.every((id) => typeof id === 'string'))
    throw new Error('features/installed-modules.json must contain a string modules array')

  const ids = installed.modules
  await assertInstalledFeatureBoundaries(root)
  const manifests = await Promise.all(
    ids.map(async (id) => {
      const featureDirectory = join(root, 'features', id)
      const descriptorPath = join(featureDirectory, 'module.config.ts')
      if (!existsSync(descriptorPath))
        throw new Error(`Installed module ${id} is missing ${relative(root, descriptorPath)}`)

      const imported: unknown = await import(`${pathToFileURL(descriptorPath).href}?registry`)
      if (!isRecord(imported))
        throw new Error(`Installed module ${id} must default-export its manifest`)
      const manifest = parsePlatformModuleManifest(imported.default, id)
      if (manifest.id !== id)
        throw new Error(`Installed module ${id} descriptor declares mismatched ID ${manifest.id}`)

      validatePackageManifest(
        featureDirectory,
        'server',
        manifest.server.package,
        manifest.server.migrations.map(({ name }) => name),
      )
      validatePackageManifest(featureDirectory, 'nuxt', manifest.nuxt.package)
      await assertManifestCompositionBoundaries(root, manifest)
      return manifest
    }),
  )

  const validated = validatePlatformModuleManifests(manifests, coreModuleValidationAuthorities)
  validateDeploymentDependencies(root, validated)
  const persistenceRoutines = await Promise.all(
    validated.flatMap((manifest) =>
      manifest.server.persistenceOperations.map(async (operation) => {
        const sql = readFileSync(
          join(root, 'features', manifest.id, 'server', 'migrations', operation.migration),
          'utf8',
        )
        return {
          ...(await canonicalizePersistenceRoutineSql({
            moduleId: manifest.id,
            operationId: operation.id,
            revision: operation.revision,
            mode: operation.mode,
            sql,
          })),
          migration: operation.migration,
        }
      }),
    ),
  )
  return { manifests: validated, persistenceRoutines } satisfies InstalledModuleRegistryInput
}

export function generateRegistryFiles(
  input: readonly PlatformModuleManifest[] | InstalledModuleRegistryInput,
) {
  const manifests = Array.isArray(input) ? input : input.manifests
  const persistenceRoutines = Array.isArray(input) ? [] : input.persistenceRoutines
  const sorted = validatePlatformModuleManifests(manifests, coreModuleValidationAuthorities)
  return new Map<string, string>([
    [generatedRegistryPaths[0], renderApiRoutes(sorted)],
    [generatedRegistryPaths[1], renderActivityProviders(sorted)],
    [generatedRegistryPaths[2], renderWorkerResources(sorted)],
    [generatedRegistryPaths[3], renderMigrations(sorted)],
    [generatedRegistryPaths[4], renderEsiOperations(sorted)],
    [generatedRegistryPaths[5], renderPersistenceOperations(sorted, persistenceRoutines)],
    [generatedRegistryPaths[6], renderModuleRuntime(sorted)],
    [generatedRegistryPaths[7], renderNuxtModules(sorted)],
    [generatedRegistryPaths[8], renderNuxtContributions(sorted)],
    [generatedRegistryPaths[9], renderNavigation(sorted)],
  ])
}

function validatePackageManifest(
  featureDirectory: string,
  kind: 'server' | 'nuxt',
  expected: string,
  migrations: readonly string[] = [],
) {
  const packagePath = join(featureDirectory, kind, 'package.json')
  if (!existsSync(packagePath)) throw new Error(`Module package is missing ${packagePath}`)
  const packageJson: unknown = JSON.parse(readFileSync(packagePath, 'utf8'))
  if (!isRecord(packageJson)) throw new Error(`${packagePath} must contain a JSON object`)
  if (packageJson.name !== expected)
    throw new Error(`${packagePath} must declare package name ${expected}`)
  if (!Array.isArray(packageJson.files) || !packageJson.files.includes('dist'))
    throw new Error(`${packagePath} files must include dist`)
  if (!isRecord(packageJson.exports) || !('.' in packageJson.exports))
    throw new Error(`${packagePath} must export its runtime`)
  if (kind !== 'server') return

  if (!packageJson.files.includes('migrations'))
    throw new Error(`${packagePath} files must include migrations`)
  if (!('./migrations/*' in packageJson.exports))
    throw new Error(`${packagePath} must export ./migrations/*`)
  for (const migration of migrations) {
    const migrationPath = join(featureDirectory, 'server', 'migrations', migration)
    if (!existsSync(migrationPath)) throw new Error(`Module migration is missing ${migrationPath}`)
  }
}

function validateDeploymentDependencies(
  root: string,
  manifests: readonly PlatformModuleManifest[],
) {
  const rootPackage = readPackageJson(join(root, 'package.json'))
  const apiPackage = readPackageJson(join(root, 'api/package.json'))
  const expectedServer = new Set(manifests.map((manifest) => manifest.server.package))
  const expectedNuxt = new Set(manifests.map((manifest) => manifest.nuxt.package))
  const rootDependencies = dependencyNames(rootPackage)
  const apiDependencies = dependencyNames(apiPackage)
  const actualServer = new Set(
    [...apiDependencies].filter(
      (name) =>
        name !== '@eve-space/platform-module-server' && /^@eve-space\/.+-server$/.test(name),
    ),
  )
  const actualNuxt = new Set(
    [...rootDependencies].filter(
      (name) => name !== '@eve-space/platform-module-nuxt' && /^@eve-space\/.+-nuxt$/.test(name),
    ),
  )

  assertExactDependencies('API feature server', actualServer, expectedServer)
  assertExactDependencies('root feature Nuxt', actualNuxt, expectedNuxt)
  for (const packageName of expectedNuxt)
    if (apiDependencies.has(packageName))
      throw new Error(`API dependencies must not include feature Nuxt package ${packageName}`)
  for (const packageName of expectedServer)
    if (rootDependencies.has(packageName))
      throw new Error(`Root dependencies must not include feature server package ${packageName}`)
}

function readPackageJson(path: string) {
  const value: unknown = JSON.parse(readFileSync(path, 'utf8'))
  if (!isRecord(value)) throw new Error(`${path} must contain a JSON object`)
  return value
}

function dependencyNames(packageJson: Record<string, unknown>) {
  return new Set(isRecord(packageJson.dependencies) ? Object.keys(packageJson.dependencies) : [])
}

function assertExactDependencies(label: string, actual: Set<string>, expected: Set<string>) {
  const missing = [...expected].filter((name) => !actual.has(name))
  const extra = [...actual].filter((name) => !expected.has(name))
  if (missing.length || extra.length)
    throw new Error(
      `${label} dependencies differ from installed modules (missing: ${missing.join(', ') || 'none'}; extra: ${extra.join(', ') || 'none'})`,
    )
}

function renderApiRoutes(manifests: readonly PlatformModuleManifest[]) {
  const routes = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.routes.map((route, routeIndex) => ({
      manifest,
      route,
      binding: `module${moduleIndex}Route${routeIndex}`,
    })),
  )
  const imports = renderServerImports(
    routes.map(({ manifest, route, binding }) => ({
      packageName: manifest.server.package,
      exportName: route.exportName,
      localName: `${binding}Factory`,
    })),
  )
  const platformImports = routes.length
    ? [
        "import { platformModuleRouteComposers } from '../../platform/module-route-composition.js'",
        "import { createPlatformModuleRouteCapabilities } from '../../platform/module-route-capabilities.js'",
      ]
        .filter(Boolean)
        .join('\n') + '\n'
    : ''
  const factories = routes.map(
    ({ manifest, route, binding }) =>
      `const ${binding} = ${binding}Factory(createPlatformModuleRouteCapabilities(${quote(manifest.id)}, ${quote(route.id)}, ${JSON.stringify(route.coreDataProducts ?? [])} as const))\n`,
  )
  const chain = routes.map(
    ({ manifest, route, binding }) =>
      `\n  .route(\n    ${quote(route.namespace)},\n    platformModuleRouteComposers[${quote(route.authorization)}](\n      ${quote(manifest.id)},\n      { audience: ${quote(route.audience)}, requiredPermission: ${quote(route.requiredPermission)} },\n      ${binding},\n    ),\n  )`,
  )
  const composition = routes.length ? `${platformImports}${imports}\n${factories.join('')}\n` : '\n'
  return `${generatedHeader}import { Hono } from 'hono'\n${composition}export const installedModuleRoutes = new Hono()${chain.join('')}\n`
}

function renderActivityProviders(manifests: readonly PlatformModuleManifest[]) {
  const providers = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.activityProviders.map((provider, providerIndex) => ({
      manifest,
      provider,
      binding: `module${moduleIndex}ActivityProvider${providerIndex}`,
    })),
  )
  const imports = renderServerImports(
    providers.map(({ manifest, provider, binding }) => ({
      packageName: manifest.server.package,
      exportName: provider.exportName,
      localName: `${binding}Factory`,
    })),
  )
  const platformImport = providers.length
    ? "import { createPlatformModuleActivityProviderCapabilities } from '../../platform/module-activity-provider-capabilities.js'\n"
    : ''
  const descriptors: PlatformInstalledActivityProviderDescriptor[] = providers.map(
    ({ manifest, provider }) => ({
      moduleId: manifest.id,
      providerId: provider.id,
      coreDataProducts: provider.coreDataProducts ?? [],
      audience: provider.audience,
      requiredPermission: provider.requiredPermission,
      freshness: provider.freshness,
      pageIds: manifest.nuxt.pages.map(({ id }) => id),
      persistenceOperations: provider.persistenceOperations,
      invoke: undefined as never,
    }),
  )
  const rendered = descriptors.length
    ? `[${descriptors
        .map((descriptor, index) => {
          const binding = providers[index]!.binding
          return `\n  { moduleId: ${quote(descriptor.moduleId)}, providerId: ${quote(descriptor.providerId)}, coreDataProducts: ${JSON.stringify(descriptor.coreDataProducts)} as const, audience: ${quote(descriptor.audience)}, requiredPermission: ${quote(descriptor.requiredPermission)}, freshness: { staleAfterSeconds: ${descriptor.freshness.staleAfterSeconds} }, pageIds: [${descriptor.pageIds.map(quote).join(', ')}], persistenceOperations: ${JSON.stringify(descriptor.persistenceOperations)} as const, invoke: (context) => ${binding}Factory(createPlatformModuleActivityProviderCapabilities(${quote(descriptor.moduleId)}, ${quote(descriptor.providerId)}, context, ${JSON.stringify(descriptor.coreDataProducts)} as const))(context) },`
        })
        .join('')}\n]`
    : '[]'
  return `${generatedHeader}import type { PlatformInstalledActivityProviderDescriptor } from '@eve-space/platform-module-contract'\n${platformImport}${imports}\nexport const installedModuleActivityProviders =\n  ${rendered} as const satisfies readonly PlatformInstalledActivityProviderDescriptor[]\n`
}

function renderWorkerResources(manifests: readonly PlatformModuleManifest[]) {
  const resources = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.resources.map((resource, resourceIndex) => ({
      manifest,
      resource,
      binding: `module${moduleIndex}Resource${resourceIndex}`,
    })),
  )
  const imports = renderServerImports(
    resources.map(({ manifest, resource, binding }) => ({
      packageName: manifest.server.package,
      exportName: resource.exportName,
      localName: binding,
    })),
  )
  const descriptors = resources.map(({ manifest, resource, binding }) => {
    const coreDataProducts = JSON.stringify(resource.coreDataProducts ?? [])
    const batch = resource.batch
      ? ` batch: { mode: ${quote(resource.batch.mode)}, operationId: ${quote(resource.batch.operationId)} },`
      : ''
    const dependent = resource.dependentOperationIds?.length
      ? ` dependentOperationIds: ${JSON.stringify(resource.dependentOperationIds)},`
      : ''
    return `({ moduleId: ${quote(manifest.id)}, resourceId: ${quote(resource.id)}, operationId: ${quote(resource.operationId)}, coreDataProducts: ${coreDataProducts} as const,${dependent}${batch} subjectKind: ${quote(resource.subjectKind)}, materializationIntervalSeconds: ${resource.materializationIntervalSeconds}, eligibility: { kind: ${quote(resource.eligibility.kind)} }, persistence: ${JSON.stringify(resource.persistence)} as const, implementation: ${binding} satisfies PlatformResourceImplementationForProducts<typeof ${binding}, readonly ${coreDataProducts}> } as const)`
  })
  const rendered = descriptors.length ? `[${descriptors.join(', ')}]` : '[]'
  const importedTypes = resources.length
    ? 'PlatformInstalledResourceDescriptor, PlatformResourceImplementationForProducts'
    : 'PlatformInstalledResourceDescriptor'
  return `${generatedHeader}import type { ${importedTypes} } from '@eve-space/platform-module-contract'\n${imports}export const installedModuleResources =\n  ${rendered} as const satisfies readonly PlatformInstalledResourceDescriptor[]\n`
}

function renderMigrations(manifests: readonly PlatformModuleManifest[]) {
  const moduleIds = manifests.map(({ id }) => id)
  const migrations: PlatformInstalledModuleMigrationDescriptor[] = manifests.flatMap((manifest) =>
    manifest.server.migrations.map((migration) => ({ moduleId: manifest.id, ...migration })),
  )
  const renderedModuleIds = moduleIds.length
    ? `[${moduleIds.map(quote).join(', ')}] as const`
    : '[] as const'
  const renderedMigrations = migrations.length
    ? `[${migrations
        .map(
          (migration) =>
            `\n  { moduleId: ${quote(migration.moduleId)}, name: ${quote(migration.name)} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const migrationAssignment = migrations.length
    ? `${renderedMigrations} satisfies readonly PlatformInstalledModuleMigrationDescriptor[]`
    : `\n  ${renderedMigrations} satisfies readonly PlatformInstalledModuleMigrationDescriptor[]`
  return `${generatedHeader}import type { PlatformInstalledModuleMigrationDescriptor } from '@eve-space/platform-module-contract'\n\nexport const installedModuleIds = ${renderedModuleIds}\nexport const installedModuleMigrations =${migrationAssignment}\n`
}

function renderEsiOperations(manifests: readonly PlatformModuleManifest[]) {
  const operations = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.esiOperations.map((operation, operationIndex) => ({
      manifest,
      operation,
      binding: `module${moduleIndex}EsiOperation${operationIndex}`,
    })),
  )
  const imports = renderServerImports(
    operations.map(({ manifest, operation, binding }) => ({
      packageName: manifest.server.package,
      exportName: operation.exportName,
      localName: binding,
    })),
  )
  const catalog = operations.length
    ? `{${operations
        .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding},`)
        .join('')}\n}`
    : '{}'
  const definitions = operations.length
    ? `{${operations
        .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding},`)
        .join('')}\n}`
    : '{}'
  return `${generatedHeader}import type { PlatformEsiOperationContract } from '@eve-space/platform-module-contract'\nimport type { PlatformExecutableEsiOperationDefinition } from '@eve-space/platform-module-server'\n${imports}\nexport const installedModuleEsiOperationDefinitions = ${definitions} as const satisfies Record<\n  string,\n  PlatformExecutableEsiOperationDefinition\n>\n\nexport const installedModuleEsiOperationCatalog = ${catalog.replaceAll(/(module\d+EsiOperation\d+)/g, '$1.contract')} as const satisfies Record<\n  string,\n  PlatformEsiOperationContract\n>\n\nexport const installedModuleEsiSdkOperationIds = {${operations
    .map(({ operation, binding }) => `\n  ${quote(operation.id)}: ${binding}.sdkOperationId,`)
    .join('')}${operations.length ? '\n' : ''}} as const satisfies Record<string, string>\n`
}

function renderPersistenceOperations(
  manifests: readonly PlatformModuleManifest[],
  routines: readonly ReviewedPersistenceRoutine[],
) {
  const operations = manifests.flatMap((manifest, moduleIndex) =>
    manifest.server.persistenceOperations.map((operation, operationIndex) => ({
      manifest,
      operation,
      binding: `module${moduleIndex}PersistenceOperation${operationIndex}`,
      routine: routines.find(
        ({ identity }) =>
          identity.moduleId === manifest.id && identity.operationId === operation.id,
      ),
    })),
  )
  for (const { manifest, operation, routine } of operations)
    if (!routine)
      throw new Error(
        `Missing reviewed persistence routine ${manifest.id}/${operation.id} during registry generation`,
      )
  if (routines.length !== operations.length)
    throw new Error('Reviewed persistence routine inventory differs from module declarations')

  const imports = renderServerImports(
    operations.map(({ manifest, operation, binding }) => ({
      packageName: manifest.server.package,
      exportName: operation.exportName,
      localName: binding,
    })),
  )
  const descriptors = operations.map(({ manifest, operation, binding, routine }) => {
    const grants = persistenceOperationGrants(manifest, operation.id)
    return `{ moduleId: ${quote(manifest.id)}, operationId: ${quote(operation.id)}, method: ${quote(operation.method)}, revision: ${operation.revision}, mode: ${quote(operation.mode)}, migration: ${quote(operation.migration)}, schemaName: ${quote(routine!.identity.schemaName)}, routineName: ${quote(routine!.identity.routineName)}, definitionFingerprint: ${quote(routine!.definitionFingerprint)}, definition: ${binding} satisfies PlatformPersistenceOperationDefinition<${quote(operation.id)}, ${quote(operation.method)}, ${operation.revision}, ${quote(operation.mode)}>, grants: ${JSON.stringify(grants)} }`
  })
  const contractFingerprint = createModulePersistenceContractFingerprint(
    operations.map(({ manifest, operation, routine }) => ({
      moduleId: manifest.id,
      operationId: operation.id,
      method: operation.method,
      revision: operation.revision,
      mode: operation.mode,
      migration: operation.migration,
      schemaName: routine!.identity.schemaName,
      routineName: routine!.identity.routineName,
      definitionFingerprint: routine!.definitionFingerprint,
      grants: persistenceOperationGrants(manifest, operation.id),
    })),
    manifests.map(({ id }) => id),
  )
  const list = operations.length ? `[\n  ${descriptors.join(',\n  ')},\n]` : '[]'
  const catalog = operations.length
    ? `{${operations
        .map(({ manifest, operation }, index) => {
          const identity = `${manifest.id}/${operation.id}`
          return `\n  ${quote(identity)}: installedModulePersistenceOperations[${index}]!,`
        })
        .join('')}\n}`
    : '{}'
  const factories = renderPersistenceCapabilityFactories(manifests, operations)
  const platformImports = operations.length
    ? `import {\n  bindPlatformPersistenceOperation,\n  type PlatformInstalledPersistenceOperationDescriptor,\n  type PlatformPersistenceOperationDefinition,\n  type PlatformPersistenceOperationInvoker,\n} from '@eve-space/platform-module-server'\n`
    : "import type { PlatformInstalledPersistenceOperationDescriptor, PlatformPersistenceOperationInvoker } from '@eve-space/platform-module-server'\n"
  return `${generatedHeader}${platformImports}${imports}\nexport const installedModulePersistenceOperations = ${list} as const satisfies readonly PlatformInstalledPersistenceOperationDescriptor[]\n\nexport const installedModulePersistenceContractFingerprint = ${quote(contractFingerprint)}\n\nexport const installedModulePersistenceOperationCatalog = ${catalog} as const\n${factories}`
}

function renderPersistenceCapabilityFactories(
  manifests: readonly PlatformModuleManifest[],
  operations: readonly {
    readonly manifest: PlatformModuleManifest
    readonly operation: PlatformModuleManifest['server']['persistenceOperations'][number]
  }[],
) {
  const operationIndex = new Map(
    operations.map(({ manifest, operation }, index) => [`${manifest.id}/${operation.id}`, index]),
  )
  const factories = manifests.flatMap((manifest, moduleIndex) => [
    ...manifest.server.routes.map((route, routeIndex) => ({
      name: `createModule${moduleIndex}Route${routeIndex}Persistence`,
      group: 'routes' as const,
      key: `${manifest.id}/${route.id}`,
      manifest,
      references: route.persistenceOperations,
    })),
    ...manifest.server.activityProviders.map((provider, providerIndex) => ({
      name: `createModule${moduleIndex}ActivityProvider${providerIndex}Persistence`,
      group: 'activityProviders' as const,
      key: `${manifest.id}/${provider.id}`,
      manifest,
      references: provider.persistenceOperations,
    })),
    ...manifest.server.resources.flatMap((resource, resourceIndex) => [
      {
        name: `createModule${moduleIndex}Resource${resourceIndex}ProjectionPersistence`,
        group: 'resourceProjections' as const,
        key: `${manifest.id}/${resource.id}`,
        manifest,
        references: resource.persistence.projection,
      },
      {
        name: `createModule${moduleIndex}Resource${resourceIndex}MaterializationPersistence`,
        group: 'resourceMaterializations' as const,
        key: `${manifest.id}/${resource.id}`,
        manifest,
        references: resource.persistence.materialization,
      },
    ]),
  ])
  const declarations = factories
    .map(({ name, manifest, references }) => {
      const methods = references.map(({ operationId }) => {
        const index = operationIndex.get(`${manifest.id}/${operationId}`)
        if (index === undefined)
          throw new Error(`Missing persistence binding ${manifest.id}/${operationId}`)
        const operation = manifest.server.persistenceOperations.find(
          ({ id }) => id === operationId,
        )!
        return `${quote(operation.method)}: bindPlatformPersistenceOperation(installedModulePersistenceOperations[${index}]!, invoke),`
      })
      const parameter = methods.length > 0 ? 'invoke' : '_invoke'
      const renderedMethods = methods.length ? `\n    ${methods.join('\n    ')}\n  ` : ''
      return `\nexport function ${name}(${parameter}: PlatformPersistenceOperationInvoker) {\n  return {${renderedMethods}}\n}\n`
    })
    .join('')
  const groups = [
    'routes',
    'activityProviders',
    'resourceProjections',
    'resourceMaterializations',
  ] as const
  const catalogs = groups
    .map((group) => {
      const entries = factories
        .filter((factory) => factory.group === group)
        .map(({ key, name }) => `\n    ${quote(key)}: ${name},`)
        .join('')
      return `\n  ${group}: {${entries}${entries ? '\n  ' : ''}},`
    })
    .join('')
  return `${declarations}\nexport const installedModulePersistenceCapabilityFactories = {${catalogs}\n} as const\n`
}

function persistenceOperationGrants(manifest: PlatformModuleManifest, operationId: string) {
  const referencesOperation = (references: readonly { readonly operationId: string }[]) =>
    references.some((reference) => reference.operationId === operationId)
  return {
    routes: manifest.server.routes
      .filter((route) => referencesOperation(route.persistenceOperations))
      .map(({ id }) => id),
    activityProviders: manifest.server.activityProviders
      .filter((provider) => referencesOperation(provider.persistenceOperations))
      .map(({ id }) => id),
    resourceProjections: manifest.server.resources
      .filter((resource) => referencesOperation(resource.persistence.projection))
      .map(({ id }) => id),
    resourceMaterializations: manifest.server.resources
      .filter((resource) => referencesOperation(resource.persistence.materialization))
      .map(({ id }) => id),
  }
}

function renderModuleRuntime(manifests: readonly PlatformModuleManifest[]) {
  const definitions: PlatformInstalledModuleDefinition[] = manifests.map(
    ({ id, defaultEnabled }) => ({
      moduleId: id,
      defaultEnabled,
    }),
  )
  const navigation: PlatformNavigationDefault[] = [
    ...coreNavigationDefaults,
    ...manifests.flatMap((manifest) =>
      manifest.nuxt.navigation.map(({ id, placement, order }) => ({
        ownerId: manifest.id,
        navigationId: id,
        placement,
        order,
      })),
    ),
  ].toSorted(compareRuntimeNavigation)
  const renderedDefinitions = definitions.length
    ? `[${definitions
        .map(
          ({ moduleId, defaultEnabled }) =>
            `\n  { moduleId: ${quote(moduleId)}, defaultEnabled: ${defaultEnabled} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const renderedNavigation = navigation.length
    ? `[${navigation
        .map(
          ({ ownerId, navigationId, placement, order }) =>
            `\n  { ownerId: ${quote(ownerId)}, navigationId: ${quote(navigationId)}, placement: ${quote(placement)}, order: ${order} },`,
        )
        .join('')}\n] as const`
    : '[] as const'
  const definitionAssignment = definitions.length
    ? ` ${renderedDefinitions} satisfies readonly PlatformInstalledModuleDefinition[]`
    : `\n  ${renderedDefinitions} satisfies readonly PlatformInstalledModuleDefinition[]`
  return `${generatedHeader}import type {\n  PlatformInstalledModuleDefinition,\n  PlatformNavigationDefault,\n} from '@eve-space/platform-module-contract'\n\nexport const installedModuleDefinitions =${definitionAssignment}\nexport const platformNavigationDefaults = ${renderedNavigation} satisfies readonly PlatformNavigationDefault[]\n`
}

function renderNuxtModules(manifests: readonly PlatformModuleManifest[]) {
  const imports = manifests.map(
    (manifest, index) => `import module${index} from ${quote(manifest.nuxt.package)}\n`,
  )
  const moduleBindings = manifests.map((_manifest, index) => `module${index}`).join(', ')
  return `${generatedHeader}${imports.join('')}export const installedNuxtModules = [${moduleBindings}] as const\n`
}

function renderNuxtContributions(manifests: readonly PlatformModuleManifest[]) {
  const contributions: PlatformNuxtContributionDescriptor[] = manifests.map((manifest) => ({
    moduleId: manifest.id,
    defaultIcon: manifest.icon,
    pages: manifest.nuxt.pages,
    navigation: manifest.nuxt.navigation,
    ...(manifest.nuxt.exposed ? { exposed: manifest.nuxt.exposed } : {}),
  }))
  const rendered = contributions.length ? JSON.stringify(contributions, undefined, 2) : '[]'
  return `${generatedHeader}import type { PlatformNuxtContributionDescriptor } from '@eve-space/platform-module-contract'\n\nexport const installedNuxtContributions =\n  ${rendered} as const satisfies readonly PlatformNuxtContributionDescriptor[]\n`
}

function renderNavigation(manifests: readonly PlatformModuleManifest[]) {
  const navigation: PlatformInstalledNavigation[] = manifests
    .flatMap((manifest) =>
      manifest.nuxt.navigation.map((entry) => ({
        moduleId: manifest.id,
        ...entry,
        icon: entry.icon ?? manifest.icon,
      })),
    )
    .toSorted(compareNavigation)
  if (navigation.length === 0)
    return `${generatedHeader}import type { PlatformInstalledNavigation } from '@eve-space/platform-module-contract'\n\nexport const installedModuleNavigation =\n  [] as const satisfies readonly PlatformInstalledNavigation[]\n`
  return `${generatedHeader}import type { PlatformInstalledNavigation } from '@eve-space/platform-module-contract'\n\nexport const installedModuleNavigation = [${navigation.map(renderNavigationEntry).join('')}\n] as const satisfies readonly PlatformInstalledNavigation[]\n`
}

function renderNavigationEntry(entry: PlatformInstalledNavigation) {
  return `\n  {\n    moduleId: ${quote(entry.moduleId)},\n    id: ${quote(entry.id)},\n    label: ${quote(entry.label)},\n    description: ${quote(entry.description)},\n    to: ${quote(entry.to)},\n    icon: ${quote(entry.icon)},\n    audience: ${quote(entry.audience)},\n    placement: ${quote(entry.placement)},\n    order: ${entry.order},\n    pageName: ${quote(entry.pageName)},\n  },`
}

function compareNavigation(left: PlatformInstalledNavigation, right: PlatformInstalledNavigation) {
  return (
    left.order - right.order ||
    compareStable(left.moduleId, right.moduleId) ||
    compareStable(left.id, right.id)
  )
}

function compareRuntimeNavigation(
  left: PlatformNavigationDefault,
  right: PlatformNavigationDefault,
) {
  return (
    platformNavigationPlacements.indexOf(left.placement) -
      platformNavigationPlacements.indexOf(right.placement) ||
    left.order - right.order ||
    compareStable(left.ownerId, right.ownerId) ||
    compareStable(left.navigationId, right.navigationId)
  )
}

function renderServerImports(
  imports: readonly { packageName: string; exportName: string; localName: string }[],
) {
  const specifiersByPackage = new Map<string, string[]>()
  for (const { packageName, exportName, localName } of imports) {
    const specifiers = specifiersByPackage.get(packageName) ?? []
    specifiers.push(`${exportName} as ${localName}`)
    specifiersByPackage.set(packageName, specifiers)
  }
  return [...specifiersByPackage]
    .map(([packageName, specifiers]) => {
      if (specifiers.length === 1) return `import { ${specifiers[0]} } from ${quote(packageName)}\n`
      const renderedSpecifiers = specifiers.map((specifier) => `  ${specifier},`).join('\n')
      return `import {\n${renderedSpecifiers}\n} from ${quote(packageName)}\n`
    })
    .join('')
}

function quote(value: string) {
  const backslash = String.fromCodePoint(92)
  const escapedSingleQuote = String.raw`\'`
  const escapedNewline = String.raw`\n`
  const escaped = value
    .replaceAll(backslash, backslash.repeat(2))
    .replaceAll("'", escapedSingleQuote)
    .replaceAll('\n', escapedNewline)
  return "'" + escaped + "'"
}

function parsePlatformModuleManifest(value: unknown, moduleId: string): PlatformModuleManifest {
  if (
    !isRecord(value) ||
    typeof value.id !== 'string' ||
    typeof value.icon !== 'string' ||
    typeof value.defaultEnabled !== 'boolean' ||
    !isRecord(value.server) ||
    typeof value.server.package !== 'string' ||
    !Array.isArray(value.server.routes) ||
    !Array.isArray(value.server.migrations) ||
    !Array.isArray(value.server.persistenceOperations) ||
    !Array.isArray(value.server.resources) ||
    !Array.isArray(value.server.esiOperations) ||
    !Array.isArray(value.server.activityProviders) ||
    !isRecord(value.nuxt) ||
    typeof value.nuxt.package !== 'string' ||
    !Array.isArray(value.nuxt.pages) ||
    !Array.isArray(value.nuxt.navigation) ||
    (value.nuxt.exposed !== undefined && !isRecord(value.nuxt.exposed))
  )
    throw new Error(`Installed module ${moduleId} must default-export its manifest`)
  return value as unknown as PlatformModuleManifest
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

export function assertOutputPath(root: string, path: string) {
  const output = resolve(root, path)
  const relativeOutput = relative(root, output)
  if (
    relativeOutput.startsWith(`..${sep}`) ||
    relativeOutput === '..' ||
    dirname(output) === output
  )
    throw new Error(`Generated output escapes the repository: ${path}`)
  return output
}
