import { QUERY_GC_TIME } from '../utils/colada-options'

export const QUERY_POLICY = {
  authConfig: { gcTime: QUERY_GC_TIME, staleTime: 5 * 60_000 },
  authSession: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  character: { gcTime: QUERY_GC_TIME, staleTime: 5 * 60_000 },
  characterAssetRoutes: {
    gcTime: QUERY_GC_TIME,
    staleTime: 60 * 60_000,
  },
  characterAssets: { gcTime: QUERY_GC_TIME, staleTime: 60 * 60_000 },
  characterAttributes: { gcTime: QUERY_GC_TIME, staleTime: 120_000 },
  characterClones: { gcTime: QUERY_GC_TIME, staleTime: 120_000 },
  characterFinanceBalance: {
    gcTime: QUERY_GC_TIME,
    staleTime: 2 * 60_000,
  },
  characterFinanceContractBids: {
    gcTime: QUERY_GC_TIME,
    staleTime: 5 * 60_000,
  },
  characterFinanceContractItems: {
    gcTime: QUERY_GC_TIME,
    staleTime: 60 * 60_000,
  },
  characterFinanceContracts: {
    gcTime: QUERY_GC_TIME,
    staleTime: 5 * 60_000,
  },
  characterFinanceJournal: {
    gcTime: QUERY_GC_TIME,
    staleTime: 60 * 60_000,
  },
  characterFinanceOpenOrders: {
    gcTime: QUERY_GC_TIME,
    staleTime: 20 * 60_000,
  },
  characterFinanceOrderHistory: {
    gcTime: QUERY_GC_TIME,
    staleTime: 60 * 60_000,
  },
  characterFinanceTransactions: {
    gcTime: QUERY_GC_TIME,
    staleTime: 60 * 60_000,
  },
  characterHistory: { gcTime: QUERY_GC_TIME, staleTime: 5 * 60_000 },
  characterImplants: { gcTime: QUERY_GC_TIME, staleTime: 120_000 },
  characterOverview: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  characterRoster: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  characterSkillQueue: { gcTime: QUERY_GC_TIME, staleTime: 120_000 },
  characterSkills: { gcTime: QUERY_GC_TIME, staleTime: 5 * 60_000 },
  corporation: { gcTime: QUERY_GC_TIME, staleTime: 5 * 60_000 },
  corporationAllianceHistory: { gcTime: QUERY_GC_TIME, staleTime: 5 * 60_000 },
  mailDetail: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  mailHeaders: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  mailLabels: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  mailRecipientResolution: {
    gcTime: QUERY_GC_TIME,
    staleTime: 60 * 60_000,
  },
  mailRecipientSearch: {
    gcTime: QUERY_GC_TIME,
    staleTime: 60 * 60_000,
  },
  mailingLists: { gcTime: QUERY_GC_TIME, staleTime: 120_000 },
  organizationActivities: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationAudit: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationCompliance: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationContext: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationExceptions: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationPermissionBundles: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationPermissionCatalog: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationReviewerDirectory: { gcTime: 0, staleTime: 15_000 },
  organizationReviewerEntry: { gcTime: 0, staleTime: 0 },
  organizationReviewerTarget: { gcTime: 0, staleTime: 0 },
  organizationRoles: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  organizationRosterCoverage: { gcTime: QUERY_GC_TIME, staleTime: 30_000 },
  staticTypeDetail: { gcTime: QUERY_GC_TIME, staleTime: 24 * 60 * 60_000 },
  systemStatus: { gcTime: QUERY_GC_TIME, staleTime: 15_000 },
} as const
