import { QUERY_GC_TIME } from '../utils/colada-options'

export const QUERY_POLICY = {
  authConfig: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  authSession: { staleTime: 30_000, gcTime: QUERY_GC_TIME },
  systemStatus: { staleTime: 15_000, gcTime: QUERY_GC_TIME },
  character: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  characterRoster: { staleTime: 30_000, gcTime: QUERY_GC_TIME },
  characterOverview: { staleTime: 30_000, gcTime: QUERY_GC_TIME },
  characterAttributes: { staleTime: 120_000, gcTime: QUERY_GC_TIME },
  characterSkillQueue: { staleTime: 120_000, gcTime: QUERY_GC_TIME },
  characterSkills: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  characterClones: { staleTime: 120_000, gcTime: QUERY_GC_TIME },
  characterImplants: { staleTime: 120_000, gcTime: QUERY_GC_TIME },
  characterHistory: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  characterAssets: { staleTime: 60 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceBalance: { staleTime: 2 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceJournal: { staleTime: 60 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceTransactions: { staleTime: 60 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceOpenOrders: { staleTime: 20 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceOrderHistory: { staleTime: 60 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceContracts: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceContractItems: { staleTime: 60 * 60_000, gcTime: QUERY_GC_TIME },
  characterFinanceContractBids: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  mailHeaders: { staleTime: 30_000, gcTime: QUERY_GC_TIME },
  mailDetail: { staleTime: 30_000, gcTime: QUERY_GC_TIME },
  mailLabels: { staleTime: 30_000, gcTime: QUERY_GC_TIME },
  mailingLists: { staleTime: 120_000, gcTime: QUERY_GC_TIME },
  mailRecipientResolution: { staleTime: 60 * 60_000, gcTime: QUERY_GC_TIME },
  mailRecipientSearch: { staleTime: 60 * 60_000, gcTime: QUERY_GC_TIME },
  corporation: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  corporationAllianceHistory: { staleTime: 5 * 60_000, gcTime: QUERY_GC_TIME },
  staticTypeDetail: { staleTime: 24 * 60 * 60_000, gcTime: QUERY_GC_TIME },
} as const
