type DocumentedCacheBehavior =
  | { kind: 'relative'; seconds: number }
  | { kind: 'daily-utc'; hour: number; minute: number }
  | { kind: 'runtime-only' }
  | { kind: 'none' }

type DocumentedRateLimit =
  | { kind: 'legacy-only' }
  | { kind: 'declared'; group: string; maximumTokens: number; window: string }

interface EsiOperationMetadata {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE'
  path: string
  esiOperationId: string
  minimumCompatibilityDate: string
  requiredScope: string | null
  cache: DocumentedCacheBehavior
  supportsConditionalRequests: boolean
  rateLimit: DocumentedRateLimit
  maximumBatchSize?: number
}

export const esiMetadataReview = {
  explorerUrl: 'https://developers.eveonline.com/api-explorer',
  reviewedAt: '2026-09-03',
  requestedCompatibilityDate: '2026-08-23',
  resolvedCompatibilityDate: '2026-08-18',
} as const

export const esiOperationMetadata = {
  status: {
    method: 'GET',
    path: '/status',
    esiOperationId: 'GetStatus',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'relative', seconds: 30 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'declared', group: 'status', maximumTokens: 600, window: '15m' },
  },
  'public-character': {
    method: 'GET',
    path: '/characters/{character_id}',
    esiOperationId: 'GetCharactersDetail',
    minimumCompatibilityDate: '2026-06-09',
    requiredScope: null,
    cache: { kind: 'relative', seconds: 86_400 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'public-corporation': {
    method: 'GET',
    path: '/corporations/{corporation_id}',
    esiOperationId: 'GetCorporationsCorporationId',
    minimumCompatibilityDate: '2026-07-21',
    requiredScope: null,
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'public-alliance': {
    method: 'GET',
    path: '/alliances/{alliance_id}',
    esiOperationId: 'GetAlliancesAllianceId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'universe-races': {
    method: 'GET',
    path: '/universe/races',
    esiOperationId: 'GetUniverseRaces',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'daily-utc', hour: 11, minute: 5 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'universe-bloodlines': {
    method: 'GET',
    path: '/universe/bloodlines',
    esiOperationId: 'GetUniverseBloodlines',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'daily-utc', hour: 11, minute: 5 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'wallet-balance': {
    method: 'GET',
    path: '/characters/{character_id}/wallet',
    esiOperationId: 'GetCharactersCharacterIdWallet',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-wallet.read_character_wallet.v1',
    cache: { kind: 'relative', seconds: 120 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-wallet',
      maximumTokens: 150,
      window: '15m',
    },
  },
  'wallet-journal': {
    method: 'GET',
    path: '/characters/{character_id}/wallet/journal',
    esiOperationId: 'GetCharactersCharacterIdWalletJournal',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-wallet.read_character_wallet.v1',
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-wallet',
      maximumTokens: 150,
      window: '15m',
    },
  },
  'wallet-transactions': {
    method: 'GET',
    path: '/characters/{character_id}/wallet/transactions',
    esiOperationId: 'GetCharactersCharacterIdWalletTransactions',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-wallet.read_character_wallet.v1',
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-wallet',
      maximumTokens: 150,
      window: '15m',
    },
  },
  'market-orders': {
    method: 'GET',
    path: '/characters/{character_id}/orders',
    esiOperationId: 'GetCharactersCharacterIdOrders',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-markets.read_character_orders.v1',
    cache: { kind: 'relative', seconds: 1_200 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'market-order-history': {
    method: 'GET',
    path: '/characters/{character_id}/orders/history',
    esiOperationId: 'GetCharactersCharacterIdOrdersHistory',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-markets.read_character_orders.v1',
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'character-contracts': {
    method: 'GET',
    path: '/characters/{character_id}/contracts',
    esiOperationId: 'GetCharactersCharacterIdContracts',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-contracts.read_character_contracts.v1',
    cache: { kind: 'relative', seconds: 300 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-contract',
      maximumTokens: 600,
      window: '15m',
    },
  },
  'character-contract-items': {
    method: 'GET',
    path: '/characters/{character_id}/contracts/{contract_id}/items',
    esiOperationId: 'GetCharactersCharacterIdContractsContractIdItems',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-contracts.read_character_contracts.v1',
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-contract',
      maximumTokens: 600,
      window: '15m',
    },
  },
  'character-contract-bids': {
    method: 'GET',
    path: '/characters/{character_id}/contracts/{contract_id}/bids',
    esiOperationId: 'GetCharactersCharacterIdContractsContractIdBids',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-contracts.read_character_contracts.v1',
    cache: { kind: 'relative', seconds: 300 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-contract',
      maximumTokens: 600,
      window: '15m',
    },
  },
  'mail-headers': {
    method: 'GET',
    path: '/characters/{character_id}/mail',
    esiOperationId: 'GetCharactersCharacterIdMail',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.read_mail.v1',
    cache: { kind: 'relative', seconds: 30 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
    maximumBatchSize: 25,
  },
  'mail-message': {
    method: 'GET',
    path: '/characters/{character_id}/mail/{mail_id}',
    esiOperationId: 'GetCharactersCharacterIdMailMailId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.read_mail.v1',
    cache: { kind: 'relative', seconds: 30 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'mail-labels': {
    method: 'GET',
    path: '/characters/{character_id}/mail/labels',
    esiOperationId: 'GetCharactersCharacterIdMailLabels',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.read_mail.v1',
    cache: { kind: 'relative', seconds: 30 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'mail-lists': {
    method: 'GET',
    path: '/characters/{character_id}/mail/lists',
    esiOperationId: 'GetCharactersCharacterIdMailLists',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.read_mail.v1',
    cache: { kind: 'relative', seconds: 120 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'mail-send': {
    method: 'POST',
    path: '/characters/{character_id}/mail',
    esiOperationId: 'PostCharactersCharacterIdMail',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.send_mail.v1',
    cache: { kind: 'none' },
    supportsConditionalRequests: false,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'mail-create-label': {
    method: 'POST',
    path: '/characters/{character_id}/mail/labels',
    esiOperationId: 'PostCharactersCharacterIdMailLabels',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.organize_mail.v1',
    cache: { kind: 'none' },
    supportsConditionalRequests: false,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'mail-update': {
    method: 'PUT',
    path: '/characters/{character_id}/mail/{mail_id}',
    esiOperationId: 'PutCharactersCharacterIdMailMailId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.organize_mail.v1',
    cache: { kind: 'none' },
    supportsConditionalRequests: false,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'mail-delete': {
    method: 'DELETE',
    path: '/characters/{character_id}/mail/{mail_id}',
    esiOperationId: 'DeleteCharactersCharacterIdMailMailId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.organize_mail.v1',
    cache: { kind: 'none' },
    supportsConditionalRequests: false,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'mail-delete-label': {
    method: 'DELETE',
    path: '/characters/{character_id}/mail/labels/{label_id}',
    esiOperationId: 'DeleteCharactersCharacterIdMailLabelsLabelId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-mail.organize_mail.v1',
    cache: { kind: 'none' },
    supportsConditionalRequests: false,
    rateLimit: { kind: 'declared', group: 'char-social', maximumTokens: 600, window: '15m' },
  },
  'character-search': {
    method: 'GET',
    path: '/characters/{character_id}/search',
    esiOperationId: 'GetCharactersCharacterIdSearch',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-search.search_structures.v1',
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'character-cspa-charge': {
    method: 'POST',
    path: '/characters/{character_id}/cspa',
    esiOperationId: 'PostCharactersCharacterIdCspa',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-characters.read_contacts.v1',
    cache: { kind: 'none' },
    supportsConditionalRequests: false,
    rateLimit: {
      kind: 'declared',
      group: 'char-detail',
      maximumTokens: 600,
      window: '15m',
    },
    maximumBatchSize: 100,
  },
  attributes: {
    method: 'GET',
    path: '/characters/{character_id}/attributes',
    esiOperationId: 'GetCharactersCharacterIdAttributes',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-skills.read_skills.v1',
    cache: { kind: 'relative', seconds: 120 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-detail',
      maximumTokens: 600,
      window: '15m',
    },
  },
  'skill-queue': {
    method: 'GET',
    path: '/characters/{character_id}/skillqueue',
    esiOperationId: 'GetCharactersCharacterIdSkillqueue',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-skills.read_skillqueue.v1',
    cache: { kind: 'relative', seconds: 120 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-detail',
      maximumTokens: 600,
      window: '15m',
    },
  },
  'character-clones': {
    method: 'GET',
    path: '/characters/{character_id}/clones',
    esiOperationId: 'GetCharactersCharacterIdClones',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-clones.read_clones.v1',
    cache: { kind: 'relative', seconds: 120 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-location',
      maximumTokens: 1_200,
      window: '15m',
    },
  },
  'character-implants': {
    method: 'GET',
    path: '/characters/{character_id}/implants',
    esiOperationId: 'GetCharactersCharacterIdImplants',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-clones.read_implants.v1',
    cache: { kind: 'relative', seconds: 120 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-detail',
      maximumTokens: 600,
      window: '15m',
    },
  },
  skills: {
    method: 'GET',
    path: '/characters/{character_id}/skills',
    esiOperationId: 'GetCharactersCharacterIdSkills',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-skills.read_skills.v1',
    cache: { kind: 'relative', seconds: 60 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-detail',
      maximumTokens: 600,
      window: '15m',
    },
  },
  location: {
    method: 'GET',
    path: '/characters/{character_id}/location',
    esiOperationId: 'GetCharactersCharacterIdLocation',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-location.read_location.v1',
    cache: { kind: 'relative', seconds: 5 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-location',
      maximumTokens: 1_200,
      window: '15m',
    },
  },
  ship: {
    method: 'GET',
    path: '/characters/{character_id}/ship',
    esiOperationId: 'GetCharactersCharacterIdShip',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: 'esi-location.read_ship_type.v1',
    cache: { kind: 'relative', seconds: 5 },
    supportsConditionalRequests: true,
    rateLimit: {
      kind: 'declared',
      group: 'char-location',
      maximumTokens: 1_200,
      window: '15m',
    },
  },
  'employment-history': {
    method: 'GET',
    path: '/characters/{character_id}/corporationhistory',
    esiOperationId: 'GetCharactersCharacterIdCorporationhistory',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'relative', seconds: 86_400 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'universe-resolve-names': {
    method: 'POST',
    path: '/universe/names',
    esiOperationId: 'PostUniverseNames',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'runtime-only' },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
    maximumBatchSize: 1_000,
  },
  'universe-resolve-ids': {
    method: 'POST',
    path: '/universe/ids',
    esiOperationId: 'PostUniverseIds',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'runtime-only' },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
    maximumBatchSize: 500,
  },
  'corporation-alliance-history': {
    method: 'GET',
    path: '/corporations/{corporation_id}/alliancehistory',
    esiOperationId: 'GetCorporationsCorporationIdAlliancehistory',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'corporation-npc-list': {
    method: 'GET',
    path: '/corporations/npccorps',
    esiOperationId: 'GetCorporationsNpccorps',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'daily-utc', hour: 11, minute: 5 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'universe-solar-system': {
    method: 'GET',
    path: '/universe/systems/{system_id}',
    esiOperationId: 'GetUniverseSystemsSystemId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'daily-utc', hour: 11, minute: 5 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'universe-station': {
    method: 'GET',
    path: '/universe/stations/{station_id}',
    esiOperationId: 'GetUniverseStationsStationId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'daily-utc', hour: 11, minute: 5 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'universe-type': {
    method: 'GET',
    path: '/universe/types/{type_id}',
    esiOperationId: 'GetUniverseTypesTypeId',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'daily-utc', hour: 11, minute: 5 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
  },
  'bulk-affiliation': {
    method: 'POST',
    path: '/characters/affiliation',
    esiOperationId: 'PostCharactersAffiliation',
    minimumCompatibilityDate: '2020-01-01',
    requiredScope: null,
    cache: { kind: 'relative', seconds: 3_600 },
    supportsConditionalRequests: true,
    rateLimit: { kind: 'legacy-only' },
    maximumBatchSize: 1_000,
  },
} as const satisfies Record<string, EsiOperationMetadata>
