export const platformQueryAdmissionScopes = [
  {
    admissionScope: 'organization:v1:alpha:member:alpha.view',
    audience: 'member',
    authorization: 'authenticated-session',
    moduleId: 'alpha',
    requiredPermission: 'alpha.view',
    routeId: 'alpha-summary',
    sectionId: 'skills',
  },
  {
    admissionScope: 'organization:v1:alpha:member:alpha.view',
    audience: 'member',
    authorization: 'owned-character',
    moduleId: 'alpha',
    requiredPermission: 'alpha.view',
    routeId: 'alpha-record',
    sectionId: 'skills',
  },
  {
    admissionScope: 'organization:v1:mail:member:mail.view',
    audience: 'member',
    authorization: 'owned-character',
    moduleId: 'mail',
    requiredPermission: 'mail.view',
    routeId: 'mail-route',
  },
  {
    admissionScope: 'organization:v1:mail:member:mail.view',
    audience: 'member',
    authorization: 'authenticated-session',
    moduleId: 'mail',
    requiredPermission: 'mail.view',
    routeId: 'mail-summary',
  },
] as const
