import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    clearMocks: true,
    environment: 'node',
    env: {
      DATABASE_URL: 'postgres://localhost:5432/eve_space',
    },
    include: ['tests/**/*.test.ts'],
    exclude: ['tests/integration/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      include: [
        'src/deployment-organization.ts',
        'src/deployment-installation-settings.ts',
        'src/character-history-service.ts',
        'src/character-skills-service.ts',
        'src/middleware/auth-session.ts',
        'src/middleware/module-enablement.ts',
        'src/middleware/module-authorization.ts',
        'src/middleware/owned-character.ts',
        'src/routes/characters.ts',
        'src/routes/admin.ts',
        'src/routes/modules.ts',
        'src/platform/module-settings.ts',
        'src/platform/module-route-capabilities.ts',
        'src/platform/collection-state.ts',
        'src/platform/collection-state-store.ts',
        'src/platform/resource-eligibility.ts',
        'src/sso-routes.ts',
        'src/routes/status.ts',
        'src/system-status-service.ts',
        'src/wallet-service.ts',
        'src/db/locks.ts',
        'src/db/migration-validation.ts',
        'src/esi-policy.ts',
        'src/esi-resilience/catalog.ts',
        'src/esi-resilience/catalog-validation.ts',
        'src/esi-resilience/envelope.ts',
        'src/esi-resilience/identity.ts',
        'src/esi-resilience/l1.ts',
        'src/esi-resilience/namespaces.ts',
        'src/esi-resilience/operation-metadata.ts',
        'src/esi-resilience/rate-measurement.ts',
        'src/esi-resilience/resilience.ts',
        'src/esi-resilience/cooldowns.ts',
        'src/esi-resilience/telemetry.ts',
        'src/esi-resilience/transport.ts',
        'src/affiliation-sync.ts',
        'src/universe-names-service.ts',
        'src/token-service.ts',
        'src/domain-event-handlers.ts',
        'src/domain-event-status.ts',
        'src/domain-event-redrive-command.ts',
        'src/domain-event-redrive-queue.ts',
        'src/domain-events.ts',
        'src/worker-rollback-verifier.ts',
        'src/worker-readiness.ts',
        'src/queue/namespaces.ts',
        'src/queue/outbox-relay.ts',
        'src/queue/policy.ts',
        'src/queue/job-registry.ts',
        'src/queue/admission.ts',
        'src/queue/planner.ts',
        'src/queue/resource-planner.ts',
        'src/queue/scheduler.ts',
        'src/queue/status.ts',
        'src/queue/failures.ts',
        'src/queue/worker-lifecycle.ts',
      ],
      reporter: ['text', 'json-summary'],
      reportsDirectory: 'coverage',
      thresholds: {
        branches: 75,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
})
